### PR TITLE
Added new theme dorknstein.zsh-theme

### PR DESCRIPTION
**Pull request by DorkNstein**

### CODE REVIEW

**Comment by christoga** [comment]
The preview image?

**Comment by DorkNstein** [comment]
![DorkNstein zsh-theme preview image]
Format: https://drive.google.com/file/d/0B3Q7gUqrs41hbVU5X0pOMlJGSTQ/view

**Comment by mcornella** [comment]
[We can't accept more themes at the moment](https://github.com/robbyrussell/oh-my-zsh#do-not-send-us-themes). Please make a separate repo with your theme and link to it from the [external themes](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes) wiki page.

You can also add your theme as a custom theme. See [customization](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes) for instructions.

**Comment by christoga** [comment]
Can you send the zsh-theme file to my email?
`andrechristoga@gmail.com`

**Comment by mcornella** [comment]
@christoga you can get the file directly from the pull request if you go to the `Files changed` tab. Here's the direct link though: https://raw.githubusercontent.com/DorkNstein/oh-my-zsh/3dcd44b23b3bc20ba1eeb0bedb8d92b75adf6614/themes/dorknstein.zsh-theme

**Comment by christoga** [comment]
Thanks man @mcornella

**Pull request closed without merging**
