### PR TITLE
Easy-to-Merge

### LINKED ISSUE #3360: First-time users run into `chsh: option requires an argument -- 's'`
I've just tried to install oh-my-zsh for the first time on a new machine:

```sh
$ curl -L http://install.ohmyz.sh | sh
[...]
Cloning Oh My Zsh...
Cloning into '/home/dan/.oh-my-zsh'...
[...]
Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to ~/.zshrc
Copying your current PATH and adding it to the end of ~/.zshrc for you.
Time to change your default shell to zsh!
chsh: option requires an argument -- 's'
Usage: chsh [options] [LOGIN]

Options:
  -h, --help                    display this help message and exit
  -s, --shell SHELL             new login shell for the user account

$ chsh -s zsh
Password:
chsh: zsh is an invalid shell
$ chsh -s /bin/zsh
Password:
chsh: /bin/zsh is an invalid shell
````

Perhaps the automated installer should complain that `zsh` wasn't install, and offer to install it?

### LINKED ISSUE #3421: OSX: move files to the proper Trash
The command:
```sh
trash /Volumes/something/abc
```
moves the file/directory to `~/.Trash` on OS X, i.e. moves it to a different drive. It should just move the file/directory to the trash proper for the volume the file is on.

Tested on OS X Yosemite with oh-my-zsh from commit 1978a0923c864cacdc520adff83ed63f62c91073 (current `master`).

Note that Apple provides an API to move files to a proper trash via AppleScript; modules like https://www.npmjs.com/package/trash do it correctly because of that.

Originally erroneously reported at https://github.com/sindresorhus/trash/issues/17.

### LINKED ISSUE #3516: Authentication failure at "Changing shell for x"
Authentication failure when running both the wget and curl installers. It occurs both when I'm using su -c and sudo in latest Fedora, as well as when I'm running without root privileges.

### LINKED ISSUE #3715: add help to install zsh
I want to install ohmyzsh but I need to install zsh first. A brief paragraph to install zsh would be welcome. I'll be happy to add it but any help would be appreciated. Shall I do it in the README or the wiki?

### LINKED ISSUE #3855: Brew plugin needs minor update for alias bubu
When running the bubu command Homebrew issues a warning that the behavior of the upgrade command will be changing soon:

Warning: brew upgrade with no arguments will change behaviour soon!
It currently upgrades all formula but this will soon change to require '--all'.
Please update any workflows, documentation and scripts!

### LINKED ISSUE #3893: virtualenvwrapper plugin fails on ubuntu with EQUALS option set
Refering to code from #2819.
On my system I got: <pre>"/etc/bash_completion.d/virtualenvwrapper:5: = not found" </pre> when the virtualenvwrapper plugin was loaded.

The problem is that /etc/bash_completion.d/virtualenvwrapper is bash script that is run by zsh with the EQUALS option set (default I think). 
When zsh hits the <pre>if [ "$USE_FULL" == "yes" ]; then</pre> line in /etc/bash_completion.d/virtualenvwrapper it tries to do '=' expansion as described in 14.7.3 [here](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Filename-Expansion)

I managed to fix the problem by adding <pre>unsetopt EQUALS</pre> to the top of the virtualenvwrapper.plugin.zsh file but there is probably a better way to do this.

### PR DESCRIPTION
**Pull request by ncanceill**
## Easy to Merge

This branch collects PRs that are easy to merge. If you want to add a commit, please [submit a PR](https://github.com/ncanceill/oh-my-zsh/pull/new/easymerge) to [my branch](https://github.com/ncanceill/oh-my-zsh/tree/easymerge).

**Rule:** either the PR is an extremely simple fix, or it has been discussed–tested–and–signed-off.

### Status

**READY for MERGE**

This is the third Easy-to-Merge PR: see #2827 #2922

### Changelog

* Fixes #1631
* Fixes #2351
* Fixes #2723
* Fixes #2777
* Fixes #2821
* Fixes #2829
* Fixes #2856
* Fixes #2898
* Fixes #2926
* Fixes #3038, fixes #3195, fixes #3421, fixes #3445
* Fixes #3125
* Fixes #3133
* Fixes #3157
* Fixes #3158
* Fixes #3194
* Fixes #3214
* Fixes #3245
* Fixes #3360, fixes #3715, fixes #3736, fixes #3799
* Fixes #3364
* Fixes #3451
* Fixes #3516, fixes #3872
* Fixes #3542
* Fixes #3617
* Fixes #3638
* Fixes #3644
* Fixes #3663
* Fixes #3693, fixes #3923
* Fixes #3695
* Fixes #3732
* Fixes #3758
* Fixes #3787
* Fixes #3791
* Fixes #3793
* Fixes #3794
* Fixes #3816, fixes #3818, fixes #3829, fixes #3834, fixes #3840, fixes #3853, fixes #3855, fixes #3856, fixes #3883, fixes #3905
* Fixes #3837
* Fixes #3842, fixes #3898
* Fixes #3851
* Fixes #3864
* Fixes #3870
* Fixes #3871
* Fixes #3875
* Fixes #3878, fixes #3961, fixes #3984
* Fixes #3893, fixes #3981
* Fixes #3901
* Fixes #3908
* Fixes #3925
* Fixes #3955
* Fixes #3970

### CODE REVIEW

**Comment by Kriechi** [comment]
#3834 #3829 would be closed as well. Please add to the long list, same line as #3816 and #3818.

**Comment by ncanceill** [comment]
Thanks!

**Comment by Jesterovskiy** [comment]
:+1: waiting for this PR

**Comment by mcornella** [comment]
@ncanceill #3736 implemented here also closes #3360 and #3799. Please add them to the pile.

**Comment by Kriechi** [comment]
@ncanceill I think a rebase is needed to get a clean merge.
Great work so far!

**Comment by mcornella** [comment]
One more thing: the `brew upgrade --all` change will have to be excluded from this PR, the homebrew team backtracked on their decision: https://github.com/Homebrew/homebrew/commit/a45a34db0b2c66f626f3724ae9a52563b4aa94b5.

**Comment by vassyz** [comment]
Yes, my pull request #3883 needs to be removed. It's not valid anymore.

**Comment by ncanceill** [comment]
This is all rebased against current upstream.

Also, the `--all` flag mentioned by @mcornella above was removed.

Thanks guys.

**Comment by styx** [comment]
pls, sync #3125 as it was updated to latest version of mix.

**Comment by ncanceill** [comment]
Thanks @styx it is done.

**Comment by ncanceill** [comment]
@styx done

**Comment by mcornella** [comment]
Excelent job @ncanceill, really outstanding :clap: 
Minor thing: PR #3445 won't be autoclosed as is now, and the `STATUS NOT READY` should be updated once this is.
I'm throwing you some more PRs that are ready: #3133 (pick just the first commit), #3194, #3791, #3955.

**Comment by mcornella** [comment]
Let's pull in #2351 as well.

**Comment by ncanceill** [comment]
@mcornella done!

I guess this is ready for merge.

**Comment by robbyrussell** [comment]
This was pretty epic folks. Nice!

**Comment by ncanceill** [comment]
Thanks @robbyrussell, glad to help!

**Pull request merged**
