### PR TITLE
Add missing space causing parse error.

### PR DESCRIPTION
**Pull request by aliafshar**

### CODE REVIEW

**Comment by aliafshar** [comment]
Was getting an error on install and on starting zsh.

**Comment by ncanceill** [comment]
@robbyrussell there was a typo in #3986, please merge this ASAP to fix

**Comment by oryband** [comment]
yup, kinda crashes zsh now
please merge!

**Comment by fredr** [comment]
:+1:

**Comment by mcornella** [comment]
Please add `fixes #4009, fixes #4010, fixes #4011` to your PR description so those duplicates are automatically closed when this PR is merged.

**Comment by Kevin-Lee** [comment]
This closes #4018, #4019, #4020, #4021 and #4022 as well.

**Comment by leepa** [comment]
Can we get this merged asap?

**Comment by webmaster128** [comment]
shellcheck would have found that one. Has someone an idea how to automatically shellcheck PRs in the future?

**Comment by Kevin-Lee** [comment]
Probably using some CI service might be helpful (e.g. [Semaphore](https://semaphoreci.com/), [Travis](https://travis-ci.org/), [Codeship](https://codeship.com/), etc.)? I'm not sure if there's any CI service supporting `shellcheck` though.

**Comment by Kevin-Lee** [comment]
@aliafshar For your convenience, you can simply add the following line to your PR description.
```
fixes #4009, fixes #4010, fixes #4011, fixes #4018, closes #4019, fixes #4020, closes #4021 and fixes #4022
```

**Comment by webmaster128** [comment]
@Kevin-Lee afaik you can [install Ubuntu](https://github.com/randombit/botan/blob/master/.travis.yml#L21) packages on Travis. I think Travis runs [Ubuntu 12.04](https://travis-ci.org/randombit/botan/jobs/66330812#L284) which does not have shellcheck. Shellcheck comes in utopic and trusty-backports. But it should be possible to get it from a PPA.

**Comment by Kevin-Lee** [comment]
@webmaster128 If so, I recommend Semaphore because it has Ubuntu 14.04 and you can even choose 12.04 if you want whereas Travis has only Ubuntu 12.04. In fact, I found this one. https://semaphoreci.com/docs/how-to-install-dependency-from-ppa.html So yeah there is a way to run `shellcheck` I think. :smile:

**Comment by CodingFabian** [comment]
how about merging this? its not that there are not hundreds of users which are wondering why their config broke and a growing number of issues created.

**Comment by adamantivm** [comment]
Merge please?

**Comment by Kevin-Lee** [comment]
@webmaster128 I was trying to set up CI for oh-my-zsh using `shellcheck`. Could you please tell me if what I did was correct?

```shell
shellcheck -s zsh **/*.zsh 
```
If so, that shows so many issues. I tested on Ubuntu 14.04 `shellcheck` version 0.3.3 and I also tried it on Mac OS X but `shellcheck` installed using `Homebrew` doesn't seem to support `zsh` although its version is 0.3.7.

Anyway, it shows so many issues so I'm not sure if we can simply have CI for this.

**Comment by webmaster128** [comment]
@Kevin-Lee The command looks good. Version 0.3.3 should be good for now.

Try this one to get things started:

    find ./ -not -path "./plugins/*" -name "*.zsh" -exec shellcheck -s zsh --exclude=SC2034 {} \;

This excludes `plugins` for now. SC2034 is unused variables, which can be ignored for now.

**Comment by robbyrussell** [comment]
My apologies. I got a little merge happy after a few glasses of wine last night. 

:-1:

**Comment by tehmaspc** [comment]
happy dance; that was quick; funny to see all the duplicate PRs :)

**Comment by leepa** [comment]
@robbyrussell thanks for merging - however it highlights an issue. There needs to be people able to merge outside of your time zone. The popularity of this has meant my entire working day this was broken. Now, I'm able to patch/fix things myself - however lots won't.

**Comment by oshybystyi** [comment]
+1 for @leepa suggestion

**Comment by oryband** [comment]
:+1: for @leepa . Suggestions:
1. move oh-my-zsh to an organization with multiple collaborators
2. travis tests (or other CI options)
3. coveralls to make the community push towards better coverage

bonus tip: don't drink and merge

**Pull request merged**
