### PR TITLE
delete update.lock first incase it already exist

### PR DESCRIPTION
**Pull request by ccqpein**
Fix check_for_upgrade does not work on shell init

delete update.lock first incase it already exist

[issue 7036](https://github.com/robbyrussell/oh-my-zsh/issues/7036)

### CODE REVIEW

**Comment by D-sha** [comment]
I'm wondering if this would be better fixed by removing the final `rmdir $ZSH/log/update.lock` outside the final 'fi' thus ensuring it is always deleted?

**Comment by ccqpein** [comment]
The probable	cause of this problem happened on my side might be something wrong in final if-fi make script exit before final `rmdir $ZSH/log/update.lock` runs. If we move `rmdir $ZSH/log/update.lock` outside and exit accidentally in if-fi, we still do not delete `$ZSH/log/update.lock`. And this problem will happen next time. However, `$ZSH/log/update.lock` will be deleted next time, and at next-next time, everything will be fine. But we lose second update chance.

**Comment by D-sha** [comment]
This would defeat the purpose of the lock, would it not? If you opened two shells at the same time the second would delete the lock and both would try to update?
On looking at it I think that massive if block needs rewriting....

**Comment by mcornella** [comment]
I recently pushed a fix for the lock not being deleted. This is no longer necessary.

**Pull request closed without merging**
