### PR TITLE
Add FirewallD plugin

### PR DESCRIPTION
**Pull request by robjtede**
Could be too opinionated but this is what I use for firewalld.

### CODE REVIEW

**Comment by robjtede** [comment]
do new plugins _require_ a readme?

**Comment by mcornella** [comment]
Yes that's the goal. You can look at the [`tig` plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/tig/README.md).

**Comment by robjtede** [comment]
Readme added

**Comment by mcornella** [comment]
That's perfect thanks!

**Pull request merged**
