### PR TITLE
adding optionnal zsh install for debian

### PR DESCRIPTION
**Pull request by aversag**
hi
I've installed ohmyzsh several times and always getting error because the server didn't have zsh installed
so I added a test in the install script
hope it'll help!
thank you

### CODE REVIEW

**Comment by mcornella** [comment]
Hi @aversag, we won't install zsh from the install script. This project needs to support every platform and if we add automatic installation for one platform we'll end up adding it for all of them, and that's not a good situation to be in. We put installation instructions in [the wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH) and that's all we can do about it.

Thank you for trying to help.

**Comment by aversag** [comment]
ok thank you
so why not just checking if zsh is installed ? if not exit

**Comment by mcornella** [comment]
That's definitely comming on the near future, as we move towards a fully-zsh install script.

**Comment by apjanke** [comment]
There's a PR for checking whether zsh is installed now: #4241.

**Comment by mcornella** [comment]
Please close this issue

**Pull request closed without merging**
