### PR TITLE
Add plugin README template

### PR DESCRIPTION
**Pull request by D-sha**
Add a default plugin readme template

I thought it may be helpful to have a template for plugin README's
then plugins can be required to have a readme before being merged.

Does anyone else think is a good idea?
Comments on format or content?

### CODE REVIEW

**Comment by grikomsn** [comment]
As commented on https://github.com/robbyrussell/oh-my-zsh/issues/7175#issuecomment-425757996, it might be a good idea to make several kinds of readme templates for different kinds of plugins. It's a great start, though. 👍

**Comment by mcornella** [comment]
I'm hesitant to merge this because it would mean having another file in the OMZ directory, I'd rather have this in the wiki. But I like the template! I think it covers most plugin types. Thanks!

**Comment by dimensi0n** [comment]
Is this on the wiki ?

**Comment by D-sha** [comment]
No its not i kinda forgot about it sorry, What section should it go in?

**Pull request closed without merging**
