### PR TITLE
[tmux-cssh plugin] Initial version

### PR DESCRIPTION
**Pull request by moul**

### CODE REVIEW

**Comment by aimxhaisse** [comment]
:+1:

**Comment by moul** [comment]
Is there a way I can help to merge this pull-request ?
Thank you

**Comment by moul** [comment]
up

**Comment by davizucon** [comment]
@moul thank you, I tried, and worked! Its auto complete from hosts file, there is some way to auto-complete from ~/.ssh/config? 
  
I think its ok reading config file from ssh command, because  tmux-cssh depends directly from ssh, and if we config a host (user,  alias) on  ~/.ssh/config, we can use as [host1 host2 host3 host4]  parameter in tmux-cssh command.

Thanks for your help, make my day more productive and fun!

**Comment by apjanke** [comment]
As a hack, you could piggyback on Zsh's own ssh-aware host completion by changing `':hosts:_hosts'` to `':hosts:_ssh_hosts'`. Then it would pick up `~/.ssh/config` entries (sometimes; see #2737).

You'd need to call the `_ssh` function once during the plugin's initialization to force it to autoload so the `_ssh_hosts()` definition is available; it's a helper function defined inside `_ssh`. It's not documented so it probably isn't public or stable, but it seems to be around in all the recent `zsh` versions, so it'll probably work.

**Comment by davizucon** [comment]
Hi @apjanke, thanks, worked very well.
Now I am trying to add auto-complete to several hosts, like: tmux-cssh host1 host2 host3 so on.

**Comment by apjanke** [comment]
@davizucon: You might need to swap the `hosts` and `subcommands` around in the completion, or combine them using `_alternative`. The `*` indicates that it applies to all arguments; without it, it just applies to the next argument.

Have a look at [this tutorial on writing zsh completion functions](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org). I found it a lot more of a gentle introduction than the main zsh documentation, which is more of a complete reference.

**Comment by moul** [comment]
@apjanke what do you think about merging this (now 1-year old PR) that is actually working well, so we can discuss about improvements in dedicated issues ?

I'm personally using this plugin on a daily-base without encountering any issue

**Comment by apjanke** [comment]
Sounds fine to me. I don't have commit rights, though; only @robbyrussell and @mcornella do.

**Comment by mcornella** [comment]
Sorry for the delay @moul. We'll want a README as well though.

**Pull request merged**
