### PR TITLE
Add CakePHP3 plugin

### PR DESCRIPTION
**Pull request by jadb**
This adds auto-completion for the [CakePHP 3](http://cakephp.org) framework. Once merged, I will update the plugins wiki page to reflect the changes.

Thanks for considering (and hopefully merging)!

/cc @markstory @lorenzo

### CODE REVIEW

**Comment by lorenzo** [comment]
This is great! :+1:

**Comment by markstory** [comment]
Neato.

**Comment by antoniovassell** [comment]
+1

**Comment by commercial-hippie** [comment]
+1

**Comment by bracketouverte** [comment]
:+1:

**Comment by jadb** [comment]
bump

**Comment by davidyell** [comment]
Great idea! :+1:

**Comment by real34** [comment]
:+1: thanks

**Comment by jadb** [comment]
ping!

**Comment by jadb** [comment]
Thanks!!

**Pull request merged**
