### PR TITLE
Add support for just complete existant commands.

### LINKED ISSUE #3440: New commands don't completing
Zsh is unable to complete new commands. Example: If I install (or purge) a package, I need to reload the shell (hit enter, ctrl-c, etc.).

### PR DESCRIPTION
**Pull request by mhalano**
Fixes #3440

Following Marc idea I create a pull request for add rehash support, so only autocomplete works only with present commands. I believe there is no regression.

### CODE REVIEW

**Comment by apjanke** [comment]
If you put "Fixes #3440" on a line by itself in the summary for this Pull Request, that will create an auto-close link to the issue this addresses, so when this is merged, the issue will be closed, and readers can see links between the two.

**Comment by mhalano** [comment]
@apjanke Done.

**Comment by apjanke** [comment]
Looks good. Thanks!

**Comment by ncanceill** [comment]
Hi,

This technique may [impact performance](https://bbs.archlinux.org/viewtopic.php?pid=1369343#p1369343) because _"a rehash is issued on_ every _external command completion request"_ (Zsh users [#00532](http://www.zsh.org/mla/users/2011/msg00532.html)).

Consequently I believe this should be controlled by a variable indicated in the [template `.zshrc`](https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template), like we do for the [case-sensitive completion](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/completion.zsh#L14).

Also, @mhalano please do not submit PRs from your master branch — instead please create a dedicated branch for each PR. If you had done so, I could have submitted a PR to your branch to add the variable.

**Comment by mhalano** [comment]
@ncanceill I created a branch called 'add-rehash-option'. Please submit your PR. I will merge and send again the PR.

PS: I'm a new guy with this Git stuff, so please, be patient. :)

**Comment by ncanceill** [comment]
OK, I will be patient.

In order to submit a clean PR, you need to start it off the latest upstream, which is currently ff4663a6b83b8dd205da3968de4bc458abc08b2c.

To do that, you need to go into your local Git repository, which should be configured with remote origin pointing to your fork and remote upstream pointing to robbyrussell's original repository. Then:
```zsh
git fetch upstream
git checkout upstream/master
git checkout -b add-rehash-option
```
Then add your commit, push to origin and create a new PR from there.

**Comment by mhalano** [comment]
@ncanceill  Thanks for be patient. :)

I created the pull request #3817 which came from my branch.

Thanks.

**Comment by blueyed** [comment]
As stated already, this should not be enabled by default, but adding a omz config var to control this seems to be unnecessary and confusion (see my comment at https://github.com/mhalano/oh-my-zsh/pull/1/files#r43577354).

**Comment by mhalano** [comment]
Disbled by default, of course. But need to exist a easy way to enable this
option. Is a good option for user.

2015-10-31 21:36 GMT-02:00 Daniel Hahler <notifications@github.com>:

> As stated already, this should not be enabled by default, but adding a omz
> config var to control this seems to be unnecessary and confusion (see my
> comment at https://github.com/mhalano/oh-my-zsh/pull/1/files#r43577354).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbyrussell/oh-my-zsh/pull/3456#issuecomment-152780934>
> .
>



-- 
Marcos Alano
----------------------------------------------
P: Por que este email é tão curto?
R: http://five.sentenc.es
----------------------------------------------

**Comment by aude** [comment]
+1 for considering the performance hit.

**Comment by mcornella** [comment]
By popular vote I'm closing this. If you want to have this put it in your zshrc file (I have it). In the future I'll put this in the wiki FAQ, so that it is also visible.

**Pull request closed without merging**
