### PR TITLE
Add gopass autocompletion plugin

### PR DESCRIPTION
**Pull request by aanpilov**

### CODE REVIEW

**Comment by alecharp** [comment]
I just tested it locally and it's perfect! Thanks!!

**Comment by aanpilov** [comment]
Hey @alecharp, you are welcome! Can you please test updated version?

**Comment by alecharp** [comment]
I'm sorry I didn't try it sooner but it's not working anymore. Even if I don't have the same error are in the gopass issue.

**Comment by aanpilov** [comment]
@alecharp Sure, no problem. It stopped working for me too. I'll make new PR and ping you if you don't mind.

**Comment by devhell** [comment]
Is there any news on this plugin happening? :)

**Comment by fronbasal** [comment]
What is the status of this feature?

**Comment by bygui86** [comment]
hi guys, any news?
on my mac with the latest oh-my-zsh version, gopass autocomplete make some complaints :(
```
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function
_arguments:comparguments:325: can only be called from completion function
_arguments:comparguments:325: can only be called from completion function

Error: password-store is not initialized. Try 'gopass init'
_values:compvalues:11: can only be called from completion function
```

**Comment by mcornella** [comment]
There is no gopass plugin in OMZ.

**Comment by mbjarland** [comment]
Seems like this is still an issue. Also adding the output from "gopass completion zsh" to a file `_gopass` which is present in the FPATH does not solve the problem. Not sure what the issue is.

**Pull request closed without merging**
