### PR TITLE
fix nmap vuln category name

### PR DESCRIPTION
**Pull request by fdhadzh**

### CODE REVIEW

**Comment by D-sha** [comment]
@mcornella @robbyrussell This one looks good to go

--script=vulscan is not a nmap argument
--script=vuln is

http://nmap.org/book/nse-usage.html

@fdhadzh A description of why changes are needed will help to merge your request
Cheers

**Comment by fdhadzh** [comment]
script argument takes a category names or patterns. vuln is a category name. vulscan is unknown value for nmap.

**Comment by mcornella** [comment]
Thanks @D-sha your comment helped speed the process!

**Comment by D-sha** [comment]
Here to help!

**Pull request merged**
