### PR TITLE
Adds "Bullet train" theme

### PR DESCRIPTION
**Pull request by caiogondim**
You can see more details about the theme here: https://github.com/caiogondim/bullet-train-oh-my-zsh-theme

### CODE REVIEW

**Comment by rscafi** [comment]
:+1:

**Comment by Nipher** [comment]
:+1:

**Comment by lucascarvalho** [comment]
:+1:

**Comment by KhasMek** [comment]
Per [#1899](https://github.com/robbyrussell/oh-my-zsh/pull/1899#issuecomment-29688978) and the [README](https://github.com/robbyrussell/oh-my-zsh/#do-not-send-us-themes) this project is no longer accepting PR's for new themes. If you'd like to add yours to the [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes) though, that'd be fantastic!

**Pull request closed without merging**
