### PR TITLE
Detailed how to switch tabs

### PR DESCRIPTION
**Pull request by AOrobator**
Detailed how to switch tabs for OS X plugin

### CODE REVIEW

**Comment by AOrobator** [comment]
Detailed how to switch tabs for OS X plugin

**Comment by mcornella** [comment]
Wait how do you know which hotkeys work? I assume that depends on the terminal emulator you use...

**Comment by AOrobator** [comment]
This works for iTerm2, doesn't work for the Terminal app because that app isn't supported. Haven't tried it out with other emulators, but iTerm2 has a lot of popularity.

**Comment by mcornella** [comment]
Closing because this is Terminal-specific and can be found via other means.

**Pull request closed without merging**
