### PR TITLE
git auto fetch

### PR DESCRIPTION
**Pull request by slavaGanzin**
Automatically fetch changes from all remotes on cwd

Use case: I maintain a few projects as reviewer and often forget to update all repos before writing reviews.

Besides it awesomely works with git-prompt

### CODE REVIEW

**Comment by mcornella** [comment]
This will be a problem when the user is on a mobile connection where the data consumed is very important. It also doesn't have a way to prevent or cancel the update.

If you can find a good solution to that go on and add a README to the plugin as well. Thanks!

**Comment by slavaGanzin** [comment]
Maybe I can add global GIT_AUTO_FETCH which defaults to true and check it before autofetch. So you can negate it to prevent fetching?

And add GIT_AUTO_FETCH_MESSAGE
```
if [ $GIT_AUTO_FETCH_MESSAGE ]; then
echo "Fetching all remotes"
echo "To prevent autofetching(for this session): export GIT_AUTO_FETCH=false"
echo "To prevent showing this message in future 'echo GIT_AUTO_FETCH_MESSAGE=false >> ~/.zshrc"
fi
```

Or show that message if GIT_AUTO_FETCH is not set. So it can be added to your .zshrc.local file and works only on hosts where this behavior is acceptable.

**Comment by slavaGanzin** [comment]
.git/AUTO_FETCH guard file can be added to mark repo as autofetched?

And two functions:
git_autofetch_enable
git_autofetch_disable

**Comment by slavaGanzin** [comment]
@mcornella 

 https://github.com/slavaGanzin/oh-my-zsh/tree/25fcf0c265c682f092ce49a6849e5e09b38dffa9/plugins/git-auto-fetch

You always welcome to add some clarifications to my README.md

**Comment by fazlearefin** [comment]
Hi @slavaGanzin ,

I've spent about 15-20 minutes testing your plugin. And here are my comments.

**`git-auto-fetch` function**
The function `git-auto-fetch` should be renamed to `git-no-auto-fetch`. On a fresh git repo, when I run this command for the first time it says **enabled** and creates the guard file and hence stops auto fetch. However this is contradictory to the **enabled** message shown when executing the function for the first time. So either change the function name or swap the messages in the `echo`.

**Functionality of the plugin itself**
Looking at the code it looks like a `git fetch` executes only when `cd`-ing into the base dir of a git repo. I understand this is the intent of your plugin but compared to `magicmonty/bash-git-prompt` your plugin is very much limited. The following actions also need to work:

- when `cd` into a sub-directory of the same git repo from the base dir of the repo
- when directly `cd` into the sub dir of a git repo
- when staying in the same git repo and the same dir but pressing return/enter

You might be asking why the additional actions should do a `git fetch`. The reason is I am not the only person working on the branch. While I am working on the branch there might be other developers who have `git push`ed and until I do a `git fetch` I won't get the latest code.

**Comment by slavaGanzin** [comment]
@fazlearefin Many thanks for ideas and testing

I've implemented:
- when cd into a sub-directory of the same git repo from the base dir of the repo
- when directly cd into the sub dir of a git repo

And fixed wrong messaging, of course

But for:
- when staying in the same git repo and the same dir but pressing return/enter

I summon @mcornella for recommendation of suitable zle widget for that task. Mark can you help me?

**Comment by fazlearefin** [comment]
@slavaGanzin 

Thanks for implementing the new requested changes so quickly. I have tested your latest commit and here's the status:

- `git-auto-fetch` function: **OK**
- when cd into a sub-directory of the same git repo from the base dir of the repo: **OK**
- when directly cd into the sub dir of a git repo: **OK**
- when staying in the same git repo and the same dir but pressing return/enter: **Pending**

**Comment by slavaGanzin** [comment]
@fazlearefin Can you test it again, please?

**Comment by slavaGanzin** [comment]
@mcornella @fazlearefin I'm using this on a daily basis for a month and has no issues with it. So I think this PR can be merged:
# it has documentation
# it works as described
# it is optional for oh-my-zsh users, so we not forcing something

Code has a bit of "magic", but I think nobody would contribute except me

**Comment by fazlearefin** [comment]
@slavaGanzin 

Thanks for working on this feature. I tried your latest commit and it seems to have some issues. After enabling the `git-auto-fetch` plugin, when I launch a new zsh shell, I get this:

`git-fetch-all:wait:6: pid 0 is not a child of this shell`

And when I `cd` to a git repository, the shell just becomes very slow. I have to wait 4-5 seconds to type something to get any output.

**Comment by slavaGanzin** [comment]
@fazlearefin I accidentally pushed my experimental version (in which I wanted to update RPROMPT to show "fetching" message)

Now it was reversed to stable one. Please retest. I'm sorry for that situation

**Comment by slavaGanzin** [comment]
@fazlearefin @mcornella Any progress?

**Comment by fazlearefin** [comment]
@slavaGanzin Apologies for the late reply. I've tested it and I can say it works! Good job!

**Comment by slavaGanzin** [comment]
@mcornella can we merge this now?

**Comment by kolemannix** [comment]
I would use this once merged

**Comment by slavaGanzin** [comment]
@kolemannix can you test it before merge?

To avoid changing your .oh-my-zsh folder you can simply:
```
cd ~
wget https://raw.githubusercontent.com/slavaGanzin/oh-my-zsh/d2dfa69419845daebcfd20fed3253ae06faa2876/plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
echo "source ~/git-auto-fetch.plugin.zsh" >> ~/.zshrc
zsh
```

**Comment by kolemannix** [comment]
Sure; I loaded it in just now. Will use all day today and see if I have any issues. Anything specifically to test for?

**Comment by slavaGanzin** [comment]
@kolemannix Nothing specifically. Thanks

**Comment by igauravsehrawat** [comment]
Still not merged?

**Comment by fazlearefin** [comment]
i have been using the [zsh pure theme ](https://github.com/sindresorhus/pure) which has this functionality built-in.

**Comment by slavaGanzin** [comment]
> Still not merged?
@fazlearefin Because of no active maintenance of this repo, I stepped a bit further and switched to fish shell (which I highly recommend). Same plugin: https://github.com/slavaGanzin/config/blob/master/fish/functions/fish_git_auto_fetch.fish

**Comment by irvingpop** [comment]
This is a good PR and is working well for me (put in `$ZSH_CUSTOM/plugins/`) 😄  thank you @slavaGanzin for developing it!

**Comment by mcornella** [comment]
Thanks for your contribution!

**Pull request merged**
