### PR TITLE
Update z version to 5dc2a86

### PR DESCRIPTION
**Pull request by posva**
There is an old PR at #3248
That's why I'm creating a new one

Version: https://github.com/rupa/z/commit/5dc2a863ccdcefb28aaf87cc99c31c6619158ed4
Closes #3248.

### CODE REVIEW

**Comment by apjanke** [comment]
The "Closes #3248" needs to be in the body of the PR description, not just the title, for it to work properly and auto-close the referenced issue.

**Comment by apjanke** [comment]
This should close #4570, too.

**Comment by apjanke** [comment]
What version of the upstream `z.sh` does this grab? Might be nice to note that in the plugin.

**Comment by posva** [comment]
@apjanke There's unfortunately no version number :confused: 
I updated `z` again and fixed the commit

**Comment by apjanke** [comment]
Even if it's not one of the [numbered releases](https://github.com/rupa/z/releases), could we identify it with the git commit ID?

**Pull request merged**
