### PR TITLE
Remove Atom plugin

### PR DESCRIPTION
**Pull request by RobLoach**
The Atom plugin is obsolete.

See #3193

### CODE REVIEW

**Comment by mcornella** [comment]
Why was this merged? At least aliases could have been preserved, if the path logic was unnecessary...

**Comment by RobLoach** [comment]
@mcornella Your comment at https://github.com/robbyrussell/oh-my-zsh/pull/3193#issuecomment-144097896 .

**Comment by mcornella** [comment]
I was referring to the specific change of the `at` alias, not the whole plugin.

**Comment by RobLoach** [comment]
> I was referring to the specific change of the at alias, not the whole plugin.

Ah, well the whole plugin is not needed as Atom by default will accomplish what it implemented. As for the alias, building off of what you recommended, one could just use `a='atom'` or `at='atom'`.

**Comment by Tokynet** [comment]
Late to the party but yes, loosing the alias sucked

**Pull request merged**
