### PR TITLE
gulp.js plugin

### PR DESCRIPTION
**Pull request by akoenig**

### CODE REVIEW

**Comment by mmrko** [comment]
FWIW as per [gulp docs](https://github.com/gulpjs/gulp-cli/tree/master/completion) you can just add `eval "$(gulp --completion=zsh)"` to your `.zshrc`. The plugin should probably use this shorthand as well (in the same vein as the [npm plugin](https://github.com/robbyrussell/oh-my-zsh/blob/c78277fd8bda5fec87504469afdf121355876006/plugins/npm/npm.plugin.zsh)).

**Comment by akoenig** [comment]
@mmrko True story. I was aware of this solution while building my thingy. This one is starting gulp (and therefore a whole Node.js process) which causes performance problems on low-end systems like the RPi.

**Comment by mmrko** [comment]
Nice work! Yours is indeed way snappier. Maybe this could be a PR over at [gulp-cli](/gulpjs/gulp-cli). What do you think? Would help tackle gulpjs/gulp/issues/851 as well :)

**Comment by dafstone** [comment]
+1 - quick and handy.

**Comment by mmrko** [comment]
Something to take into account if you tend to split your gulp tasks into multiple files is that this will only pick up tasks defined in gulpfile.js.

**Comment by fundon** [comment]
+1, Nice

**Comment by carueda** [comment]
:+1:

**Comment by davidbakertv** [comment]
+1

**Comment by mcornella** [comment]
Hi @akoenig, please rename your completion function to `__gulp_completion` or similar, it's not good practice to use `$` on function names. 

You should also put the information of the plugin in a separate `README.md` file so that the `plugin.zsh` one only has the functionality (for example, the [sublime text](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/sublime/README.md) plugin). The copyright info is redundant, too (see #2587). 

Lastly, you can put completion in a file named `_gulp` and zsh will read it by default. That's a common and better practice for plugins that only provide autocompletion. See [adb](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/adb/_adb), [nvm](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/nvm/_nvm), [pass](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/pass/_pass) or [pip](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/pip/_pip) plugins to get the basic structure of completion files.

**Comment by macgyver** [comment]
I'm not qualified to code review an oh-my-zsh plugin but I added this to my own `~/.zshrc` and it works perfectly for all my gulp tasks, thanks!

**Comment by aforty** [comment]
+1

**Comment by ScreenDriver** [comment]
+1

**Pull request merged**
