### PR TITLE
Round 3 of batch-closing obsolete issues

### LINKED ISSUE #2755: shouldn't custom configs come after loading a theme?
A theme shouldn't be dependent on anything that the user has in custom, but the user may want to over-ride certain aspects of a theme, using some custom files.

Currently the custom files are loaded immediately before the theme.  I've switched it locally, and haven't seen any ill effects (using robbyrussell as my theme, just moving the pwd from PROMPT to RPROMPT).

### LINKED ISSUE #2942: Enable colored man on illumos/Solaris
The following patch enables proper colored man support on Solaris and illumos platforms.

diff --git a/plugins/colored-man/colored-man.plugin.zsh b/plugins/colored-man/colored-man.plugin.zsh
index 5605628..8877446 100644
--- a/plugins/colored-man/colored-man.plugin.zsh
+++ b/plugins/colored-man/colored-man.plugin.zsh
@@ -1,3 +1,22 @@
+un=`/usr/bin/uname -s`
+if [ "$un" = "SunOS" ]
+then
+	if [ ! -x ${HOME}/bin/nroff ]
+	then
+		mkdir -p ${HOME}/bin
+		cat > ${HOME}/bin/nroff <<EOF
+#!/bin/sh
+if [ -n "\$_NROFF_U" -a "\$1,\$2,\$3" = "-u0,-Tlp,-man" ]; then
+	shift
+	exec /usr/bin/nroff -u\${_NROFF_U} "\$@"
+fi
+#-- Some other invocation of nroff
+exec /usr/bin/nroff "\$@"
+EOF
+	chmod +x ${HOME}/bin/nroff
+	fi
+fi
+
 man() {
       env \
       	  LESS_TERMCAP_mb=$(printf "\e[1;31m") \
@@ -7,5 +26,8 @@ man() {
 	  LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
 	  LESS_TERMCAP_ue=$(printf "\e[0m") \
 	  LESS_TERMCAP_us=$(printf "\e[1;32m") \
+	  PAGER=/usr/bin/less \
+	  _NROFF_U=1 \
+	  PATH=${HOME}/bin:${PATH} \
 	  			   man "$@"
 }

### LINKED ISSUE #2972: per-directory-history ignores HIST_IGNORE_SPACE
I think the title says it all: the per-directory-history plugin records all history, while it should honor HIST_IGNORE_SPACE (and perhaps other history-related options).

### LINKED ISSUE #2987: symfony2 autocomplete broken
Since last commits; tabbing after ```app/console``` does nothing.

### LINKED ISSUE #3013: Error returnned when attempting to autocomplete git commands while not in a git repository
Typing: git checkout [TAB] while not inside of a git repository results in the following:
```
[nanenj]% git checkout fatal: Not a git repository (or any of the parent directories): .git
HEAD
```

When not in a git repositiory, it should fail to autocomplete and should not suggest HEAD.  The failure to autocomplete is indication enough that it's not working and as is the error returned while hitting tab destroys the prompt and makes things difficult to read.

I don't think tab completion should be returning errors.  It should either default to how zsh itself behaves or just not autocomplete at all.  Even if this isn't an 'issue' that will get resolved.  If someone could point me in the right direction of where to look so I could at least fix it to my tastes locally, that'd be awesome. 

Currently I've explored large portions of the git.zsh functions in lib, and the git plugin, but, most if not all of the obvious calls in both of these places redirect stderr to /dev/null, indicating that the behavior I'm after is actually what's intended.

### LINKED ISSUE #3015: Safer / simpler way to install
The documentation suggest manual installation is to be done overwriting `.zshrc` after Oh‑My-ZSH was installed in `.oh-my-zsh`.

I get the ZIP archive, unpacked it as `~/apps/oh-my-zsh`, edited the first not‑commented line to turn it from `export ZSH=$HOME/.oh-my-zsh` to `export ZSH="$HOME/apps/oh-my-zsh"` then added `source "$HOME/apps/oh-my-zsh/templates/zshrc.zsh-template"` the end of `.zshrc`.

Well… `$HOME/apps/` may be anything else.

I don't see a reason why the documentation suggest overwriting `.zshrc` and installing files in an hidden directory. The hidden directory is not the big point (although that's not a relevant place for this), the lack of suggesting to source the file from `.zshrc` instead of overwriting it, is the main point.

### LINKED ISSUE #3016: PAGER environment variable blindly overwritten
In `$ZSH/lib/misc.zsh` at line 12, `export PAGER="less"`, blindly overwrites the `PAGER` environment variable. This should be changed into `env_default PAGER "less"`.

### LINKED ISSUE #3024: Per directory history mess up fc
When `per-directory-history` is part of the loaded plugins, the result of `fc` is messed up. As an example, `fc -l -1 -1`, which should always display something, displays `fc: no such event: 0` whenever the Ctrl-G key was pressed any time before.

### LINKED ISSUE #3096: Images broken in themes wiki
Some of the mages appear to be broken in [wiki/Theme](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes), the links need to be fixed :lollipop:

### LINKED ISSUE #3179: the robbyrussell theme can not make difference between root and normal users

### LINKED ISSUE #3190: ugly appearance in emacs shell on  Mac osx
I use oh-my-zsh as default shell in Mac osX Terminal

when I start emacs in Terminal and run command : 

M-x: shell

in emacs, the shell opened in emacs is too ugly: 
snip20141005_4

### LINKED ISSUE #3207: Download the install script with a secured connection
The current documentation tells us to do this in order to install oh-my-zsh

```sh
curl -L http://install.ohmyz.sh | sh
```

But this is very dangerous. The content is transferred on a unsecured http channel, which means it can be modified by an attacker, or maybe it can get corrupted (TCP's checksum is very weak). Either way, there is a chance for arbitrary malicious/broken code to be executed.

It should be curled from a secured channel instead, like https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh

### LINKED ISSUE #3208: Warp point should not contain whitespace while is just  contains "s"
I don't know why but on one of my OSX I am not able to add any warp point with "s" letter in name.
Seems that \s matches not only space but also "s".
This happens only on one of my computers. What can be miss-configured?

```
git:(master) wd add ssite
 * Warp point should not contain whitespace
```

### LINKED ISSUE #3246: update wd plugin to play nice with OS X Mavericks
Fix for whitespace problem available in the wd repository: https://github.com/mfaerevaag/wd/commit/616a9b71f1d3a31b71736c7d724c1f190e3e37ff

### LINKED ISSUE #3285: "apt-get download" won't complete
I use the comand "apt-get download <package name>" a lot, but i start to type "apt-get..." and "download" option is not available. How do I fix them?

### LINKED ISSUE #3288: How to turn off git plugin
I removed git from the plugins=() line, but still get the aliases it sets up which I don't want.  I can't find uninstall instructions anywhere and it didn't stop working the way I thought was intuitive.  Please advise.

### LINKED ISSUE #3325: Cursor shows one character behind
I'm having an issue with the cursor showing one character behind where it should when using the [chrome mosh app](https://chrome.google.com/webstore/detail/mosh/ooiklbnjmhbcgemelgfhaeaocllobloj) and [chrome ssh app](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo). 

I'm accessing a Ubuntu 14.04 VPS with a vanilla `curl -L http://install.ohmyz.sh | sh` install. This does not happen when I use [putty](http://www.chiark.greenend.org.uk/~sgtatham/putty/). I suspect this is a UTF-8 issue. 

image

### LINKED ISSUE #3327: Many of the theme's screenshots not showing
Hello,

The screenshots for many of the themes aren't showing, as i'm sure you well know. As I look for new color schemes to spice up my terminal, I notice this every time. Is there any way we can get them back? Is there any way I can help with this?

Cheers!

### LINKED ISSUE #3346: Completion is repeated after sudo -s
Normal user
```
╭─alberto@nareti  ~/.oh-my-zsh  ‹master›
╰─$ pwd[CURSOR]

# after TAB completion

╭─alberto@nareti  ~/.oh-my-zsh  ‹master›
╰─$ pwd[CURSOR]
PWD       pwd       pwd_mkdb
```

Root user with ``sudo -s``
```
╭─root@nareti  ~/.oh-my-zsh  ‹master›
╰─$ pwd[CURSOR]

# after TAB completion

╭─root@nareti  ~/.oh-my-zsh  ‹master›
╰─$ pwd pwd[CURSOR]
PWD       pwd       pwd_mkdb
```

It happens with iTerm
TERM = xterm-256color
theme = bira or flazz or pygmalion
zsh 5.0.6 (x86_64-apple-darwin13.3.0) installed with brew
osx mavericks

### LINKED ISSUE #3356: complete:13: command not found: compdef
I am getting 2 instances of this error when I launch a new terminal window

```
complete:13: command not found: compdef
complete:13: command not found: compdef
complete:13: command not found: compdef
complete:13: command not found: compdef
jprice@xxx:pts/3-> /home » jprice  (0) 
```

I found this: #2315 and I have commented out line 25 in the check_for_upgrades.sh. 

I have also backed up all my dotfiles and removed them, and used a clean install of oh-my-zsh and I still seem to get it.

I'm lost as to what else to do? Any suggestions?

### LINKED ISSUE #3360: First-time users run into `chsh: option requires an argument -- 's'`
I've just tried to install oh-my-zsh for the first time on a new machine:

```sh
$ curl -L http://install.ohmyz.sh | sh
[...]
Cloning Oh My Zsh...
Cloning into '/home/dan/.oh-my-zsh'...
[...]
Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to ~/.zshrc
Copying your current PATH and adding it to the end of ~/.zshrc for you.
Time to change your default shell to zsh!
chsh: option requires an argument -- 's'
Usage: chsh [options] [LOGIN]

Options:
  -h, --help                    display this help message and exit
  -s, --shell SHELL             new login shell for the user account

$ chsh -s zsh
Password:
chsh: zsh is an invalid shell
$ chsh -s /bin/zsh
Password:
chsh: /bin/zsh is an invalid shell
````

Perhaps the automated installer should complain that `zsh` wasn't install, and offer to install it?

### LINKED ISSUE #3370: Order dependency between bundler and rails plugins
Hi,

Using both the `bundler` and `rails` plugins, order between them matters.

Here is the observed behavior:
```
#.zshrc
plugins=(bundler rails)

$ type -a rake
rake is an alias for _rake_command
rake is /usr/bin/rake
```

```
#.zshrc
plugins=(rails bundler)

$ type -a rake
rake is an alias for bundled_rake
rake is /usr/bin/rake
```

Can this be considered a bug?

Thanks :)

### LINKED ISSUE #3379: Feature request: split plugins into submodules
I really like oh-my-zsh but I feel that it's not right to have to download all the plugins, when I only use a few. 

I think the maintainer of each plugin should use the git subtree split technique to split plugins into separate repos and then add references to those repos as submodules. Oh-My-Zsh can continue to operate as usual while allowing those outside the oh-my-zsh ecosystem to use (and contribute to!) the project. 

I'm still working out the kinks but here's an example.
https://github.com/adamwong246/heck-yeah-zsh-colored-man - the colored-man plugin, split into a seperate repo. Ideally this would be maintained by the originator, in this case @moinakg. 

https://github.com/adamwong246/dotfiles - my dotfiles, which references the split repo as a submodule. 

Of course, this may introduce some extra cognitive overhead when merging and such but this approach allows for a more "federated" system of plugins.

### LINKED ISSUE #3384: encoding problem on OSX
I use Oh-My-Zsh under OSX 10.9, but german chars e.g. ä,ü,ß are not displayed correctly in the command-line:

```
phil@imac ~/Documents/ » ls
Übung 1              Übung 3
Übung 2              Übung 4
phil@imac ~/Documents/ » cd U<0308>bung\ 4
```

### LINKED ISSUE #3398: Facing the job table full or recursion limit exceeded issue
Hi,

I am facing the the issue "local: 215: job table full or recursion limit exceeded. "
When I type something, it turns to "local 63: maxium nested function level reached".

So, currently, I cannot use the terminal at all, could someone tell me how to fix that? 

Many thanks!!!!!

### LINKED ISSUE #3437: how to config the timeout time?
I found that when I excute a php script, it will quit after one hour.
How should I excute the script all the time.

### LINKED ISSUE #3439: Color themes
It would be nice to have some predefined color themes. This could be difficult to implement due to the fact that each terminal have its own way to customize but it is still a very good idea. Maybe someone could present a clever way to do that.

### LINKED ISSUE #3446: Update Error!!!
.oh-my-zsh/oh-my-zsh.sh:30: parse error near `||'

### LINKED ISSUE #3487: Theme disabled after installing powerline
here is my ```.zshrc``` file:

```
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="amuse" 

plugins=(git)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

. /usr/local/lib/python2.7/dist-packages/powerline/bindings/zsh/powerline.zsh 

```

the last line points to my powerline.zsh, and the  theme is "amuse", so instead of having something like this image 
zsh 

I got this instead

img

### LINKED ISSUE #3492: Not autocompleting named directories
Hey guys!

I've recently upgraded OMZ to the latest version, but not it won't autocomplete any of my named directories.

Any thoughts on why that might be happening?

Felipe Rocha

### LINKED ISSUE #3529: backgroud color
when i open ~/.zshrc file and change theme "ys" to "miloshadzic". 
open new windows in terminal,
whole ground font color has changed but terminal backgroud still white?
i has been found different soluction but it does't work any suggestion ?

### LINKED ISSUE #3539: tmux plugin: can't start new session
When I run `tmux` while using the tmux zsh plugin, I am unable to start a new session, just reattach to an old one. When I remove the plugin from my `.zshrc`, everything is fine. Currently using tmux 1.9a, and OS X Yosemite, though this was a problem in Mavericks too.

### LINKED ISSUE #3621: Cloud symbol not showing properly
I am using Ubuntu 14.04
I set up cloud theme and it does not show properly:
klioxyn

Please, help to fix that!

### LINKED ISSUE #3634: Can have a special man page for alias of git plugins?

### LINKED ISSUE #3720: os x 10.10 can't build cache
```bash
~|⇒  cd .oh-my-zsh/cache
⇒  ls
```
There is no cache. And I use pip ,there is no cache.

```bash
beyond@birdcat:~/.oh-my-zsh/cache|master
⇒  pip install -
```

it complets - options first ,not the name of the software. 

The version of pip is
```bash
⇒  pip --version
pip 6.0.8 from /usr/local/lib/python2.7/site-packages/pip-6.0.8-py2.7.egg (python 2.7)
```

Could you help me???

### LINKED ISSUE #3722: "aptitude upgrade" not autocompleted
I don't know if it's oh-my-szh issue, but if I type "aptitude upg" and press <Tab>, it is autocompleted as "aptitude -upgrade", because "upgrade" is not in the autocompletion list, only "full-upgrade" and "safe-upgrade" are.
Could you please fix it?

### LINKED ISSUE #3769: Whether there is support freebsd?

### LINKED ISSUE #3828: Wrong Directory
Issue: There is no directory called proxy but after p press tab its completed to proxy
```
╭─mitesh at RestrictedArea in ~ using 15-04-30 - 15:12:40 
╰─○ cd proxy 
~bin
╭─mitesh at RestrictedArea in /bin using 15-04-30 - 15:12:50 
╰─○ pwd
/bin
╭─mitesh at RestrictedArea in /bin using 15-04-30 - 15:12:55 
╰─○ 
```

### LINKED ISSUE #3855: Brew plugin needs minor update for alias bubu
When running the bubu command Homebrew issues a warning that the behavior of the upgrade command will be changing soon:

Warning: brew upgrade with no arguments will change behaviour soon!
It currently upgrades all formula but this will soon change to require '--all'.
Please update any workflows, documentation and scripts!

### LINKED ISSUE #3873: Help with maintenance and PullRequests
Hi @robbyrussell, first of all, congrats for this really nice work!

I saw that there is so much PullRequests to your repository and I wondered if you want/need some help with them. What do you think about creating a "task-force" to try to clean up some issues and Pull Requests?

Cheers!

### LINKED ISSUE #3949: brew plugin: brew upgrade require --all
`brew upgrade` will [require](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-update-my-local-packages) soon `--all`

> Warning: brew upgrade with no arguments will change behaviour soon!
> It currently upgrades all formula but this will soon change to require '--all'.
> Please update any workflows, documentation and scripts!

Should be the alias definition of the brew.plugin updated to?
`alias bubu="brew update && brew upgrade --all && brew cleanup"`

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew/brew.plugin.zsh#L2

### PR DESCRIPTION
**Pull request by mcornella**
## 62 issues closed

The reason for closing each issue is explained in the issue itself

Close #1514
Close #2113
Close #2178
Close #2354
Close #2356
Close #2755
Close #2933
Close #2942
Close #2972
Close #2985
Close #2987
Close #3013
Close #3015
Close #3016
Close #3024
Close #3064
Close #3096
Close #3107
Close #3136
Close #3179
Close #3190
Close #3207
Close #3208
Close #3212
Close #3246
Close #3249
Close #3258
Close #3285
Close #3288
Close #3306
Close #3325
Close #3346
Close #3356
Close #3360
Close #3370
Close #3379
Close #3383
Close #3384
Close #3398
Close #3437
Close #3439
Close #3446
Close #3487
Close #3492
Close #3529
Close #3539
Close #3621
Close #3634
Close #3720
Close #3722
Close #3734
Close #3769
Close #3799
Close #3816
Close #3828
Close #3829
Close #3834
Close #3855
Close #3873
Close #3883
Close #3904
Close #3949

### CODE REVIEW

**Comment by apjanke** [comment]
How about adding:

Same reasons as above:

Close #3398 
Close #3360 

The following are just helpdesk style issues that have been adequately addressed, and no further response from the posters seems likely:

Close #3720 
Close #3621 
Close #3529 
Close #3487 
Close #3446 
Close #3384 

And for these, two months and no response sounds after a partial bug report like it's not high enough priority to worry about:

Close #3539 
Close #3439

**Comment by mcornella** [comment]
Done!

**Comment by ncanceill** [comment]
Hey, still on sweeping duty?

Here is a first batch, in raw format for copy-paste:

```
* Fixes #2755
* Fixes #2972
* Fixes #3015
* Fixes #3016
* Fixes #3024
* Fixes #3179
* Fixes #3379
* Fixes #3437
* Fixes #3492
* Fixes #3634
* Fixes #3662
* Fixes #3722
* Fixes #3734
```

**Comment by mcornella** [comment]
Thanks! Updated and sorted to spot duplicates easier

**Comment by jcrben** [comment]
As far as #3356, I ran into this today so I don't think this problem is truly squashed. If you have a clear idea of what causes it and the best way to fix it, probably best to explain that in [your troubleshooting page](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting). I found a lot of suggestions which didn't work and the only one that did work was  [this](https://github.com/robbyrussell/oh-my-zsh/issues/630#issuecomment-70291622) comment from way back in issue #630.

**Comment by ncanceill** [comment]
@jcrben just [did](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#completion-problems), thanks.

**Comment by robbyrussell** [comment]
:100:

**Comment by mcornella** [comment]
:heart

**Comment by ncanceill** [comment]
Nice! Good job @mcornella ;-)

**Pull request merged**
