### PR TITLE
Add terraform completion support

### PR DESCRIPTION
**Pull request by gkze**

### CODE REVIEW

**Comment by pmoust** [comment]
@gkze works fine. Thank you

**Comment by robbyrussell** [comment]
Could you include a README for the plugin per #2640 ?

**Comment by dlsniper** [comment]
@gkze could you please update this and add the README so that it can be merged. It would be cool to have it part of the default plugins. Thank you for your work!

**Comment by gkze** [comment]
Sure thing! Totally forgot about this btw, sorry... coming right up

**Comment by gkze** [comment]
Recreated at https://github.com/robbyrussell/oh-my-zsh/pull/4216, deleted my fork on this one

**Comment by mcornella** [comment]
Please close this one

**Pull request closed without merging**
