### PR TITLE
Bring bgnotify plugin up to date with t413/zsh-background-notify

### PR DESCRIPTION
**Pull request by t413**
Changes include:
- time format now shows h/m/s (only when needed!)
- enables only with interactive shells
- adds specific kde support (via kdialog)
- adds click-through-action for OS X notifications

### CODE REVIEW

**Comment by mcornella** [comment]
@andrey-yantsen @shalecreig can you guys +1 this one?

**Comment by andrey-yantsen** [comment]
+1

**Comment by andrey-yantsen** [comment]
@mcornella you've misspelled @shalecraig's nickname :)
So... @shalecraig can you please +1 this one?

**Comment by shalecraig** [comment]
+1 whynot

**Comment by shalecraig** [comment]
(thanks, @andrey-yantsen)

**Comment by mcornella** [comment]
:sweat_smile: sorry! 
Ok, ready to merge /cc @robbyrussell

**Comment by t413** [comment]
Mistakenly closed when trying to update to include @depressiveRobot's fix t413/zsh-background-notify#6. Reopening!

**Pull request merged**
