### PR TITLE
[wd] Update wd plugin to latest

### PR DESCRIPTION
**Pull request by mfaerevaag**
Fixes overwriting of `PATH` env variable

### CODE REVIEW

**Comment by ianmarcinkowski** [comment]
Thanks for this.  It seems to resolve my problem with wd

**Comment by mfaerevaag** [comment]
Good to hear that this fixes it! Sorry for the bug 🐞

**Comment by mzanibelli** [comment]
I realised the PR was not updated with the latest commit https://github.com/mfaerevaag/wd/commit/cf71f837755d60b86f7e12d26a85b7f2e4974afc

**Comment by mfaerevaag** [comment]
Damn... 😠 Sorry about that. Submitting yet another PR...

**Pull request merged**
