### PR TITLE
Better 'bira' theme and added functions

### PR DESCRIPTION
**Pull request by shriniwas26**
- Add a useful mkcd command
- Better working of bira theme with virtualenv

### CODE REVIEW

**Comment by mcornella** [comment]
* You shouldn't modify the zshrc template. Instead, you should copy it to `~/.zshrc` and make your modifications there.
* `mkcd` already exists with the name `take`.
* The bira theme change modifies the order of the displayed information, which is IMO a breaking change. Instead, you want to copy it to the custom folder and modify it there. See [Overriding and adding themes](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes)

**Comment by shriniwas26** [comment]
Thanks for your reply. All your points are valid, but I did not understand
why the theme change would be breaking. Could you explain in a bit more
detail?
Best regards,
Shriniwas

**Comment by mcornella** [comment]
Because it modified the order of display of the virtualenv. I thought the original had the virtualenv information shown before the user information, but it looks like this was a recent change. It does make sense to put it after the git prompt. Open a new PR with just the bira change please.

**Comment by shriniwas26** [comment]
Done!
Best regards,
Shriniwas

--
Shriniwas Sharma
Software Developer, Sioux Embedded Systems, Eindhoven, The Netherlands
M.Sc. (Computer Science & Engineering), TU Eindhoven, The Netherlands
Phone & WhatsApp : +31 6 45872727

**Pull request closed without merging**
