### PR TITLE
Update the readme in accordance with PR #4617

### PR DESCRIPTION
**Pull request by ahmadawais**
Reflecting the changes in PR #4617 in the ReadMe.

### CODE REVIEW

**Comment by apjanke** [comment]
Since these doco changes should be tied to the alias changes, they could just go in the same PR. Even after you've already made a PR, you can revise it by making additional commits the the branch you based it on, or even doing `git commit --amend` to change the original commit, and then pushing that branch up to GitHub again.

**Comment by ahmadawais** [comment]
@apjanke I have found after working in repos with multiple contributors that all pull requests must be made on a per file basis to avoid any issues. 

Let me know if you'd like me to revise it.

**Comment by ahmadawais** [comment]
@apjanke I have update the PR #4617 as per your comment. Kindly merge it.

**Comment by apjanke** [comment]
Thanks.

I'm not one of the repo owners; so I can't merge it myself. That will need to wait for robbyrussell or mcornella to get to it.

**Pull request closed without merging**
