### PR TITLE
plugin: kube_ps1: colors and dynamically enable / disable

### LINKED ISSUE #7261: Plugin: kube-ps1: Do not auto-add to PROMPT
The plugin kube-ps1 do not auto add itself to the PROMPT.

It requires that we add the new prompt format after sourcing the oh-zsh code: as follow:

      kube-ps1
    )
    
    source $ZSH/oh-my-zsh.sh
    PROMPT=$PROMPT'$(kube_ps1) '

Is this expected ? How can we inject the new argument into the PROMPT automatically and in the proper position ?

### PR DESCRIPTION
**Pull request by pmoranga**
changes:
- easily customize the colors via variables
- command to switch on/off the custom prompt
- Improved documentation with example on how to append on the prompt.

Fixes #7261

### CODE REVIEW

**Comment by pmoranga** [comment]
Adds documentation regarding #7261

**Comment by brunoluiz** [comment]
Shouldn't it be auto added to `PS1/PROMPT`?

**Comment by pmoranga** [comment]
@brunoluiz Adding to PS1 / PROMPT would need to be done for each theme. So I preferred to keep same strategy from original implementation. I just added documentation on how to do it.

**Comment by brunoluiz** [comment]
> @brunoluiz Adding to PS1 / PROMPT would need to be done for each theme. So I preferred to keep same strategy from original implementation. I just added documentation on how to do it.

Ah, makes sense! Having the README already helps people out indeed. Having the kubeon and kubeoff as well.

**Comment by brunoluiz** [comment]
@pmoranga Is there any blocker on this PR? It would be awesome to have it merged

**Comment by pmoranga** [comment]
No blocker! I think maintainers from my-oh-zsh are not merging a lot of the PRs

**Comment by PeterHeja** [comment]
Just so other powerlevel9k users find this: https://github.com/jonmosco/kube-ps1/issues/56#issuecomment-431630634

**Pull request merged**
