### PR TITLE
Improve adb -s completion to show helpful info

### PR DESCRIPTION
**Pull request by mohand1993**
Currently it shows for example the following
DEVICE_ID  -- transport_id:2
Which doesn't really ease device selection, I've adapted the awk script to print device name with it's model name, see the example below
DEVICE_ID  -- Pixel_3(blueline)

### CODE REVIEW

**Comment by mcornella** [comment]
With your change I get 
```
DEVICE_ID -- potter_n(2-1.2)
```
If I change `$3` and `$4` to `$4` and `$5` I get your output. This is my `adb devices -l` output:
```
List of devices attached
ID             device usb:2-1.2 product:potter_n model:Moto_G__5__Plus device:potter_n
```

**Comment by mohand1993** [comment]
I changed it again so that it doesn't use fixed indices

**Comment by mcornella** [comment]
Good job! :+1:

**Comment by mohand1993** [comment]
Thanks

**Pull request merged**
