### PR TITLE
Adds skip-chsh flag to switch login shell step

### PR DESCRIPTION
**Pull request by marshallford**
Adds feature for #7100

### CODE REVIEW

**Comment by dimensi0n** [comment]
This is useful

**Comment by mcornella** [comment]
Hi Marshall, thanks for the PR. I pulled your changes in #5169 among many other fixes, and it could use a little more testing than what I've been able to do.

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!

**Comment by marshallford** [comment]
@mcornella Bit confused by your git flow. Looks like you manually copied my change into your own PR. Should I resolve the merge conflict here or will this PR be closed eventually? Thanks.

**Comment by mcornella** [comment]
I took your changes and another user's that also introduced similar features and made it into one commit that fit into the rest of the changes, adding both you and the other user as co-authors. See https://github.com/robbyrussell/oh-my-zsh/pull/5169/commits/6ee5b6b1dfbd15828ff698fe6f7bb9d04a54705f. This is much easier to do than merging PRs and fixing the conflicts one by one (which sometimes can't be done), while also preserving authorship.

You can keep this PR open, it will be automatically closed once #5169 is merged.

**Comment by mcornella** [comment]
Closed by #5169.

**Pull request closed without merging**
