### PR TITLE
Fix jira plugin syntax error due to merge conflict

### LINKED ISSUE #4027: jira.plugin.zsh:52: parse error near `else'
Two else branches in this if......

### PR DESCRIPTION
**Pull request by apjanke**
Fixes a syntax error due to an apparent badly-resolved merge conflict between #2898 and #2955.

Fixes #4027 
Closes #4089

### CODE REVIEW

**Comment by apjanke** [comment]
Actually, no: I don't have a setup to test this, so I'm going to leave this up to the jira plugin maintainers to resolve, instead of presuming to jump in to their code and do an "obvious" fix. Closing without merging.

**Comment by ncanceill** [comment]
Good call, but you want to call out their attention like so: @tresni

**Comment by tresni** [comment]
:+1: this is good.  Can we reopen and get it pulled in versus having me open a PR with the exact same content?

**Comment by ncanceill** [comment]
OK thanks for your input, @apjanke please reopen.

**Comment by apjanke** [comment]
Reponed.

**Comment by mateuszmnm** [comment]
Cmon! Merge already!! :D

**Comment by rileyw** [comment]
+1

**Comment by tresni** [comment]
@robbyrussell not sure what the merge schedule is, but can you please include this in the next batch to resolve the error whenever people use the JIRA plugin?  Thanks!

**Comment by dougc84** [comment]
+1

**Comment by Gaffney** [comment]
+1

**Comment by briantully** [comment]
+1

**Pull request merged**
