### PR TITLE
Gb plugin, http://getgb.io 

### PR DESCRIPTION
**Pull request by dahankzter**
I have been doing a lot of Go coding lately and I found myself sorely missing Gb completion support.
A lot of copy pasting and adapting from other plugins but it seems to work now.

### CODE REVIEW

**Comment by dahankzter** [comment]
Ping @robbyrussell this branch has not rotted yet.
Not sure who merges these days sorry if it's not you.

**Comment by robbyrussell** [comment]
Can you provide a README for this, too?

**Comment by dahankzter** [comment]
Absolutely, will do asap!

**Comment by dahankzter** [comment]
README added. It is small but covers an important caveat that the Gb user probably knows already but still important.

**Comment by dahankzter** [comment]
Does this README cover it @robbyrussell ? I can expand it but the GB site is really good.

**Comment by mcornella** [comment]
I'll make a couple of adjustments and merge it right away. Thanks!

**Comment by dahankzter** [comment]
Awesome!

**Comment by mcornella** [comment]
Almost done. @dahankzter is there a reason behind naming the plugin `getgb` instead of `gb`? If not, I'll rename it to `gb` which is less confusing.

**Comment by dahankzter** [comment]
The only reason was to not confuse with the git alias 'gb'. Gb is probably
better.

**Comment by mcornella** [comment]
@dahankzter I've submitted #5207 which adds a few improvements. Please take a look at it and I'll merge it if you +1 that.

**Comment by dahankzter** [comment]
+1 lets merge

**Pull request closed without merging**
