### PR TITLE
Removed extra % at the end of prompt for the kolo theme

### PR DESCRIPTION
**Pull request by KenanAlptekin**
I removed an extra % symbol at the end of the prompt for the kolo theme. The symbol was showing in terminal.

### CODE REVIEW

**Comment by ncanceill** [comment]
I am not sure this extra percent sign is a mistake, since it is the original Zsh prompt character.

**Comment by apjanke** [comment]
I'd think so, too. @kolo, is that trailing `%` supposed to be there?

**Comment by mcornella** [comment]
The [screenshot of the kolo theme](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#kolo) speaks for itself: the `%` needs to be there. Please close this PR.

**Comment by ncanceill** [comment]
Seconded https://github.com/robbyrussell/oh-my-zsh/pull/3643#issuecomment-136841264

**Pull request closed without merging**
