### PR TITLE
Added environment based shortcuts in symfony2 plugin

### PR DESCRIPTION
**Pull request by delphiki**
I've been using the "dev" and "prod" aliases for a while.
They've proven to be really useful when you type in commands based on symfony environment.
Credit for this tip goes to @hhamon 

The only downside I see is that the names of these aliases might not be specific enough.

### CODE REVIEW

**Comment by ncanceill** [comment]
cc @andrewtch

**Comment by andrewtch** [comment]
Wow, guys, me no expert here, although I wrote the original version of this plugin (if I recall it correctly XD)

Well, to be serios, the only advice would be to follow original ``sfsomething`` notation and use, for example, ``sfdev`` and ``sfprod`` aliases as ``dev`` and ``prod`` aliases are way too generic.

**Comment by delphiki** [comment]
That might be better now :)

**Comment by mcornella** [comment]
Merged. Care to submit a README with the list of aliases like in [this example](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/dnf/README.md)? :wink:

**Comment by delphiki** [comment]
@mcornella Thanks! I'll add the README asap.

**Pull request merged**
