### PR TITLE
Git Plugin: Add the git alias 'gtl', that list the tags that match the pattern(s)

### PR DESCRIPTION
**Pull request by ameltonyan**
Add the alias 'gtl', which does the following:

1. List the tags that match the pattern(s) passed through the argument.
2. Displays the first line of the annotation message along with the tag, or the line of the first commit message if the tag is not annotated.
3. Sorts and displays tags in descending order.

Suppose there are several tags:
v1.2.1
v2.5.1
v2.5.2
v3.5.1
...

When running gtl v2.5 this will result in

v2.5.2  -commit message 
v2.5.1  -commit message

### CODE REVIEW

**Comment by mcornella** [comment]
How does this play a role in your git workflow and do you use it often?

**Comment by ameltonyan** [comment]
Look, on one real example, we have three branches within one plugin project and each of them is used for working correspondingly with Grails 2.x, 3.x and 4.x versions. From the perspectives of business logic each branch contains the same features. But the implementations differ from Grails version to another. Daily our developers are making some improvements and development on each of them to support our old and new applications on different versions. In cases of some plugins we have more than 300 tags, some of them for 2.x, 3.x, 4.x and so on in future. So every day we face an issue of scrolling and finding the desired tags. At least on example of almost 100 developers in our company it is treated as very useful "life-hack".

**Comment by mcornella** [comment]
I've updated the alias to also use `noglob`. Now you can run it with pattern-matching characters without having to quote them. For example: `gtl *-dev` works instead of throwing a `no matches found` error.

If you're ok with the changes let me know and I'll merge this ASAP.

**Comment by ameltonyan** [comment]
Yes of course. that's cool, Thanks.

**Comment by mcornella** [comment]
:+1:

**Comment by NimoTh** [comment]
The current alias definition does not work for me. If I add quotes around the search string (as also done in git documentation), it works:
```alias gtl=gtl(){ git tag --sort=-v:refname -n -l "${1}*" }; noglob gtl```
Should this be fixed?

**Comment by mcornella** [comment]
You're right, in testing I didn't catch that because I have aliased git to `noglob git`. Fixed by https://github.com/robbyrussell/oh-my-zsh/commit/093b56a7d769d15bdcc2c5300bc4ebedc9d0a837

**Pull request merged**
