### PR TITLE
Bug fix for schrodingers VIRTUAL_ENV_DISABLE_PROMPT (7985)

### PR DESCRIPTION
**Pull request by thenoid**
This PR fixes the logic bug here: https://github.com/robbyrussell/oh-my-zsh/issues/7985

### CODE REVIEW

**Comment by mcornella** [comment]
Thanks!

**Comment by mcornella** [comment]
Hmm actually on closer inspection, it looks like the old way was specially designed so that it would only show virtualenv info *if and only if* the virtualenv built-in prompt was disabled. Otherwise, setting `VIRTUAL_ENV_DISABLE_PROMPT` would disable both the built-in and the agnoster prompt. See: https://github.com/robbyrussell/oh-my-zsh/pull/2184#issuecomment-27846156, https://github.com/robbyrussell/oh-my-zsh/pull/2239, https://github.com/robbyrussell/oh-my-zsh/commit/59c1ec80aa9b018db34078e69a27e57aea5ad761#r34515377.

**Comment by thenoid** [comment]
@mcornella hmmm, seems like perhaps we need improved logic?  As-was there was no way to disable the prompt entirely. Which I wanted to I could display the venv in my `RPROMPT`.

**Comment by Da-Juan** [comment]
I can confirm, if the virtualenv plugin is enable, no virtualenv displays in the prompt anymore and if I disable the plugin, I get both virtualenv prompts.

The virtualenv plugin sets `VIRTUAL_ENV_DISABLE_PROMPT` to 1
https://github.com/robbyrussell/oh-my-zsh/blob/6d2221e697ea4a2445202b1c32283610f84585ef/plugins/virtualenv/virtualenv.plugin.zsh#L7

**Comment by thenoid** [comment]
@mcornella Perhaps we should revert this and discuss what would be appropriate logic?  Being forced into having one-or-the-other or none-or-both seems bad. 

Perhaps oh-my-zsh should use a different boolean?  or inspect the value of `VIRTUAL_ENV_DISABLE_PROMPT`?  Since python-virtualenv is just checking for existence, oh-my-zsh could check if it is set to `disable` or something and not enable it's own virtualenv plugin?  any other value it does?

**Comment by jlucier** [comment]
I updated to the newest oh-my-zsh last night and now I'm getting the same behavior as described above (both prompts or nothing). Any fix?

**Comment by mcornella** [comment]
I've reverted the change. Perhaps we should just check if the value is 1, instead of just checking if it has a value.

**Comment by thenoid** [comment]
Yeah, representing it with Boolean logic isn't enough here - we need
 1. Disable python prompt, disable OMZ prompt
 1. Disable python prompt, enable OMZ prompt
 1. Enable python prompt, disable OMZ prompt
 
Rather than `1` I'd personally prefer something very explicit like `"YES_DISABLE_OMZ_PROMPT_TOO"` so we don't collide with people that are setting it to `1` currently.

**Comment by thenoid** [comment]
Okay - New PR: https://github.com/robbyrussell/oh-my-zsh/pull/8063

**Pull request merged**
