### PR TITLE
Fix the wrong agnoster.zsh-theme git symbol " " to "⭠"

### PR DESCRIPTION
**Pull request by shengwen1997**
Hello,

I am a Taiwanese who speak Chinese.
I recently setup the oh-my-zsh on my Ubuntu notebook and I found this error. (14.04)

Fixed

### CODE REVIEW

**Comment by mcornella** [comment]
@shengwen1997 you need to install the right ones from the repository I linked. The instructions are in this link: https://github.com/powerline/fonts/blob/master/README.rst
Then, depending on your terminal emulator, you'll have to set it up so that it uses the updated fonts.

**Comment by apjanke** [comment]
Ran in to this same issue recently with #3713. Installing the updated font that mocrnella linked to fixed it. 

It turned out that the `agnoster` section in the Themes wiki page was linking to the outdated version of the font, and causing some confusion for users. We updated the wiki page to point to the current, correct font.

Did installing updated fonts fix it for you too, @shengwen1997?

**Comment by apjanke** [comment]
I think this can be closed now. @mcornella, can this be added to one of the big cleanup lists?

**Comment by mcornella** [comment]
It sure can

**Pull request closed without merging**
