### PR TITLE
Add alias for git push to origin/current branch

### PR DESCRIPTION
**Pull request by samtgarson**
This is something I do a lot. I thought I would make an alias for it. Other people might also like it.

The wiki will need updating. :hankey:

### CODE REVIEW

**Comment by ncanceill** [comment]
Depending on your `push.default` Git config, you can make that happen with a simple `git push`. Do you not wish to do that?

Off-topic: I am listed as maintainer for the Git plugin, so please notify me by mentioning my GitHub handle when your PR involves the Git plugin.

**Comment by samtgarson** [comment]
@ncanceill hadn't thought of doing it that way round, I probably will, but I also like that this puts my mind at ease. Feel free to merge/close as you see fit.

**Comment by kevgathuku** [comment]
HEy @ncanceill @samtgarson isn't this already present as `ggpush` on https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L126

**Comment by ncanceill** [comment]
Correct! Thank you @kevgathuku and sorry I cannot remember my own commits!

So @samtgarson the `ggpush` alias should work for you.

**Comment by samtgarson** [comment]
Thanks @kevgathuku, good spot!

**Comment by kevgathuku** [comment]
You're welcome :+1:

**Pull request closed without merging**
