### PR TITLE
add vi-mode cursor mode indicator

### PR DESCRIPTION
**Pull request by japhir**
Bar for insert mode, block for normal mode. what do you think? :)

Currently would only work with urxvt, but that should be easily adjustable.

### CODE REVIEW

**Comment by paranormal** [comment]
I've being running this code for some time: https://gist.github.com/paranormal/123ae082fe141c237ba0313e993dc247
Red for NORMAL mode, the cursor switch color when you change modes.

**Comment by paranormal** [comment]
Those indicators are not so good because you have to look away from where you type. Color change is the best alternative IMHO.

**Comment by slavaGanzin** [comment]
@paranormal Can you make separate PR? Looks good for me

But:
1. cut bindkey -v
2. add $VIM_NORMAL_COLOR and $VIM_INSERT_COLOR that can override default ones

Will use yours gist now. Thanks

**Comment by slavaGanzin** [comment]
```
zle-line-init () {
  # zle -K viins
  if [ $TERM = "screen" ]; then
    echo -ne '\033P\033]12;#99FF33\007\033\\'
  elif [ $TERM != "linux" ]; then
    echo -ne "\033]12;#00FF00\007"
  fi
}; zle -N zle-line-init
```

Using zle-line-init brokes my bindings:
```
bindkey "${terminfo[kcuu1]}" fzf-history-widget
bindkey "${terminfo[kcud1]}" fzf-history-widget
```

I substitute it with plain invocation:
```echo -ne "\033]12;#00FF00\007"```
and looks it works

**Comment by slavaGanzin** [comment]
Works:
```
eval "original-vi-$(declare -f zle-line-init)"

zle-line-init () {
  zle -K viins
  if [ $TERM = "screen" ]; then
    echo -ne '\033P\033]12;#99FF33\007\033\\'
  elif [ $TERM != "linux" ]; then
    echo -ne "\033]12;#00FF00\007"
  fi
  original-vi-zle-line-init
}; zle -N zle-line-init

```

**Comment by paranormal** [comment]
Created https://github.com/robbyrussell/oh-my-zsh/pull/5857 let's talk there.

**Comment by slavaGanzin** [comment]
@mcornella Please close this issue

**Pull request closed without merging**
