### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by Qix-**
A few spelling fixes, grammatical fixes (what's with all the ellipses?), some standardization of capitalization, and a few other tweaks.

As well, I changed all standalone code fragments into proper code blocks.

I also added a missing theme image!

### CODE REVIEW

**Comment by ncanceill** [comment]
Hi, thanks for contributing.

Can you rebase?

**Comment by Qix-** [comment]
@ncanceill sorry this took so long. Done and done.

**Comment by mcornella** [comment]
:+1: /cc @robbyrussell

**Comment by robbyrussell** [comment]
Thanks @Qix- !

**Pull request merged**
