### PR TITLE
Change to use omz git_prompt* functions

### PR DESCRIPTION
**Pull request by mbologna**
Removed references for official git __git_ps1() functions.
Change to use omz function git_prompt* functions like:
- git_prompt_info() -> branch name
- git_prompt_status() -> check if untracked, modified, added,
  stashed file are in the current git repo
- git_remote_status() -> check if current repo is ahead, behind,
  or diverged.
These functions returns string automatically added to your PS1;
these are customizable via exporting ZSH_THEME_GIT_PROMPT*

### CODE REVIEW

**Comment by mbologna** [comment]
@robbyrussell can you please merge it? otherwise michelebologna.theme is broken at the moment. Thanks

**Comment by mbologna** [comment]
@mcornella @robbyrussell could you please merge it? michelebologna theme is broken. 
Thanks

**Comment by mcornella** [comment]
Ok, this solves the `command not found __git_ps1` error:
michelebologna

:+1: /cc @robbyrussell 
It will be merged soon, thanks

**Comment by robbyrussell** [comment]
@mbologna thanks for this, apologies for the latency on getting this merged

**Pull request merged**
