### PR TITLE
add git bisect aliases to git plugin

### LINKED ISSUE #3751: add `git bisect` aliases
I use these aliases in my environment:

<code>gbs</code> = <code>git bisect</code>
<code>gbss</code> = <code>git bisect start</code>
<code>gbsg</code> = <code>git bisect good</code>
<code>gbsb</code> = <code>git bisect bad</code>
<code>gbsr</code> = <code>git bisect reset</code>

### PR DESCRIPTION
**Pull request by dgirgenti**
fixes #3751

### CODE REVIEW

**Comment by ncanceill** [comment]
Hi, and thanks for contributing.

I am majorly refactoring the git plugin in #2790, go and have a look. The best course of action is to include your changes on top of the refactoring.

Easiest way (for me) to do so would be: you [submitting a PR](https://github.com/ncanceill/oh-my-zsh/pull/new/plugin-git) to [my branch](https://github.com/ncanceill/oh-my-zsh/tree/plugin-git). Remember that all aliases are now alphabetically sorted, and take the opportunity to check that you are not duplicating any.

**Comment by ncanceill** [comment]
Also, you should have used _"fixes #3751"_ instead of _"for #3751"_ in the PR description. That way, the corresponding issue will auto-close once the changes are merged.

**Comment by dgirgenti** [comment]
Ok, I'll do that pull request soon. Thanks

**Comment by ncanceill** [comment]
@robbyrussell this should have been closed by #2790, sorry I missed it, please close.

**Comment by ncanceill** [comment]
and #3751 too

**Comment by mcornella** [comment]
@ncanceill I suggest you add them to your hotfix PR #3990

**Comment by ncanceill** [comment]
Good idea, it is done.

**Pull request closed without merging**
