### PR TITLE
Update git prompt for Gentoo theme.

### PR DESCRIPTION
**Pull request by r-clancy**
Update the git prompt to include more colors, following the default zsh theme.

### CODE REVIEW

**Comment by r-clancy** [comment]
@mcornella Can this be merged?

**Comment by r-clancy** [comment]
@robbyrussell Any chance you could merge this?

**Comment by r-clancy** [comment]
@robbyrussell Could this please be merged?

**Comment by mcornella** [comment]
I don't think we can merge this one because it changes what users already expect the theme to look like. You can add your modification as a custom theme. See [customization](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes) for instructions.

**Pull request closed without merging**
