### PR TITLE
Adds the `git show` alias `gsh`

### PR DESCRIPTION
**Pull request by joelwallis**

### CODE REVIEW

**Comment by joelwallis** [comment]
First time contributing. Let me know if you find any issue with it and I'll be glad so solve.

Also, thank you very much for oh-my-zsh. It's a great tool to our productivity. 🤘

**Comment by joelwallis** [comment]
@ncanceill

**Comment by joelwallis** [comment]
@ncanceill that PR will complete three months on pending review/merge. Is there anything wrong with it? If there isn't, is there anything I could do to have it merged?

Thank you in advance for your time.

**Comment by ncanceill** [comment]
Hi, happy New Year, sorry for taking so long.

A quick Google search turned up only two `gsh` commands, neither of them seeming widely used, and there is no `gsh` alias in the OMZ codebase.

So this looks fine to me. 👍

**Comment by joelwallis** [comment]
Yay! Awesome! 🍻

**Comment by joelwallis** [comment]
One year watching a pull request! 🎉

**Comment by jeffvandyke** [comment]
Still waiting - recently installed zsh, and was about to make a PR of my own, :+1:!

**Comment by joelwallis** [comment]
@jeffvandyke yeah, I'm waiting too. No feedback at-all. But have faith, and join me in my party for two years of PR. Happening soon!

**Pull request merged**
