### PR TITLE
Added readme file for fedora plugin

### PR DESCRIPTION
**Pull request by sauravjaiswalsj**
I have created a readme file for the Fedora plugin, with steps to add the plugin to the .zsh file, and some usage examples.

Feedbacks appreciated, and happy Hacktoberfest! tada

### CODE REVIEW

**Comment by mcornella** [comment]
Hi Saurav, thanks for your contribution! Can you make it look more like the [archlinux plugin](https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/plugins/archlinux/README.md)? With tables and sections and such. You can use Sublime Text and its multiple cursors feature to quickly transform the code into a Markdown table.

Also don't forget to add a brief description of how to enable the plugin (item 2 of https://github.com/robbyrussell/oh-my-zsh/issues/7175#issue-365263634). Thanks!

**Comment by sauravjaiswalsj** [comment]
Sure, I ll do  @mcornella

**Comment by sauravjaiswalsj** [comment]
@mcornella Please have a look. Thanks!

**Comment by mcornella** [comment]
Oh wait, the fedora plugin was deprecated in favor of dnf, which [already has a README](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dnf). I'll just add a deprecated notice and link to dnf.

**Comment by mcornella** [comment]
Thanks for the effort!

**Comment by sauravjaiswalsj** [comment]
You welcome.

**Comment by sauravjaiswalsj** [comment]
That time there wasn't any dnf plugin. Never mind, it was great contributing.

**Pull request merged**
