### PR TITLE
Devanagari Om fixed in dogenpunk theme

### PR DESCRIPTION
**Pull request by sharkySharks**
I removed the incorrect Devanagari conjunct symbol at the end of Om. The dash below the letter indicates that it should join the previous letter, which is not needed in spelling Om.

### CODE REVIEW

**Comment by apjanke** [comment]
Nice. Works for me on OS X 10.9.

:+1:

**Comment by sharkySharks** [comment]
Cool, I made the change locally since I started using the dogenpunk theme, which I really like! - thought others would benefit from change as well.

**Comment by apjanke** [comment]
Cool. @dogenpunk, any objections to merging this for everyone?

**Comment by dogenpunk** [comment]
None at all. In fact I'd made the same change locally and hadn't gotten around to creating the pull request. Thanks @sharkySharks!

**Comment by sharkySharks** [comment]
Awesome! Not a problem, I like your theme!

**Comment by sharkySharks** [comment]
Just checking in on this PR, anything else needed to get it pulled in? I'd love to share it with other folks once it is updated. Thx!

**Comment by mcornella** [comment]
:+1: 
/cc @robbyrussell

**Pull request merged**
