### PR TITLE
Do not fail if tput is not available

### PR DESCRIPTION
**Pull request by fcrozat**
Fixes issue #4376

### CODE REVIEW

**Comment by apjanke** [comment]
Looks good to me, though I can only test it on the normal case where `tput` is present.

Want to hit [`tools/upgrade.sh`](https://github.com/robbyrussell/oh-my-zsh/blob/918d26e7dbcb907e673df24242c9688cd89019b9/tools/upgrade.sh#L4) with the same thing in this PR?

**Comment by fcrozat** [comment]
PR updated to handle upgrade.sh

**Comment by mcornella** [comment]
:+1: /cc @robbyrussell

**Comment by apjanke** [comment]
BTW, if you phrase it as "Fixes #4376" instead of "Fixes issue #4376", GitHub will recognize it and add an auto-close link between the PR and issue. The extra "issue" in there means it doesn't recognize it.

**Comment by apjanke** [comment]
Also BTW, does this actually work on the Synology? Because of the `set -e`, I think the script might still abort after that `tput=$(which tput)` line, since the `which` returns nonzero.

**Comment by fcrozat** [comment]
I'll fix the commit entry to help github and will update you with status on Synology (didn't double check yet)

**Comment by apjanke** [comment]
FYI, PR #4419 goes even further, ignoring all errors in the color setup. It's pretty blunt, but will get things working for now, even if it's still breaking on the Synology. Turns out, `which tput` isn't sufficient, because this code actually requires a `tput` that supports `terminfo` style capabilities.

**Pull request merged**
