### PR TITLE
Chuck Norris fortune

### PR DESCRIPTION
**Pull request by maff**
Adds Chuck Norris fortune file from http://www.k-lug.org/~kessler/projects.html. Depends on fortune (and cowsay if using `chuck_cow`) being installed (available via homebrew, apt, ...). Perfectly suitable as MOTD :)

```
Last login: Fri Jan 30 23:12:26 on ttys001
 ________________________________________
( Chuck Norris' pulse is measured on the )
( richter scale.                         )
 ----------------------------------------
        o   ^__^
         o  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

23:12:30 ~ 
$ chuck
Chuck Norris has a deep and abiding respect for human life... unless it gets in his way.

23:12:35 ~ 
$ chuck_cow
 ______________________________________
( When Chuck Norris plays Monopoly, it )
( affects the actual world economy.    )
 --------------------------------------
        o   ^__^
         o  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

### CODE REVIEW

**Comment by tejasbubane** [comment]
Please squash the commits.

**Comment by maff** [comment]
@tejasbubane done

**Comment by leyluj** [comment]
How to I get this..  Lol

**Comment by tejasbubane** [comment]
@maff Seems like you are famous now! :smiley: https://twitter.com/ohmyzsh/status/568185970857611264

**Comment by vassyz** [comment]
I'm getting this on OSX:

    ~/.oh-my-zsh/plugins/chucknorris/chucknorris.plugin.zsh:2: command not found: strfile

**Comment by maff** [comment]
I added the plugin to the Plugins page on the wiki.

@vassyz You need to install fortune (e.g. via homebrew)

**Comment by apjanke** [comment]
Made a PR to do auto-refreshing of the cache file in case additional facts about Mr. Norris are discovered. #3611 

People are probably going to keep asking about this `strfile` thing and not read the doco in the Wiki. How about testing for `fortune`'s existence inside the plugin, and giving an explanatory "please install fortune" if absent? Maybe same with `cowsay` for in chuck_cow.

**Comment by apryce** [comment]
For those that didn't know what wiki we should be looking at, they mean the plugin wiki page: https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins

**Comment by maff** [comment]
@apjanke Good idea - I'll update the plugin to check if the needed binaries are installed.

**Pull request merged**
