### PR TITLE
Add autocomplete for frontend-search

### PR DESCRIPTION
**Pull request by willmendesneto**

### CODE REVIEW

**Comment by willmendesneto** [comment]
@robbyrussell

**Comment by ncanceill** [comment]
Hi, and thanks for contributing.

Can you please get a few people to test and +1 this?

**Comment by willmendesneto** [comment]
@ncanceill , of course yes! Could you test this modification too?

**Comment by gbrennon** [comment]
tested and it is ok.

**Comment by arthurms** [comment]
+1

**Comment by willmendesneto** [comment]
@ncanceill, @robbyrussell

**Pull request merged**
