### PR TITLE
Plugin now uses completion script from docker-compose repo.

### PR DESCRIPTION
**Pull request by moncho**
It removes changes done in #3848 but it solves #3557.

### CODE REVIEW

**Comment by apjanke** [comment]
Is this license-compatible with oh-my-zsh? OMZ [is MIT licensed](https://github.com/robbyrussell/oh-my-zsh/blob/master/MIT-LICENSE.txt), but docker-compose [says it's Apache licensed](https://github.com/docker/compose/blob/8346186469eb046ebd619727ac101c83322e698b/LICENSE), which requires distribution under the same terms and with a copy of the Apache license.

**Comment by moncho** [comment]
I did not consider the original project license, sorry.

Actually the script origin is a different repo: https://github.com/sdurrheimer/docker-compose-zsh-completion , but it has been merged into docker-compose repo.

Using the original repo was already suggested on #3557, but was discarded. So maybe this PR is not  such a good idea, but it works :)

**Comment by apjanke** [comment]
Sounds like they're considering it to be part of the main project and using that license – sdurrheimer/docker-compose-zsh-completion#1. I'm not sure what the upshot of this is, but since the you know where the original code came from, maybe if you ask nicely the author would dual-license the original source under the MIT license and then you could just copy it in to OMZ and maintain it as a forked plugin (instead of a downstream synced copy).

**Comment by moncho** [comment]
@apjanke Following your suggestion, I have contacted the author and asked him about adding the MIT license. Now we wait :)

**Comment by apjanke** [comment]
Upstream has added the MIT license, per sdurrheimer/docker-compose-zsh-completion#1. You're good to go.

**Comment by apjanke** [comment]
:+1:

**Comment by jonafato** [comment]
+1 would love to see this merged

**Pull request merged**
