### PR TITLE
Update the git-extras plugin

### PR DESCRIPTION
**Pull request by nicolas-brousse**
Add missing commands into the autocompletion and reorder.

### CODE REVIEW

**Comment by nicolas-brousse** [comment]
It's not a big update :)

**Comment by mcornella** [comment]
Hi @nicolas-brousse, #3408 is more complete. Please check that one out and see if everything you change here is also changed there.

**Comment by nicolas-brousse** [comment]
Hi @mcornella, sorry for the delay.
I just read the PR #3408 and I think there is some missing:
* `obliterate`
* `pull-request`.

**Comment by mcornella** [comment]
Thanks @nicolas-brousse for taking the time to review that.

**Comment by nicolas-brousse** [comment]
:)

In this case I close my PR and let's continue talking in PR #3408.

**Pull request closed without merging**
