### PR TITLE
homestead: change key string for getting command list

### LINKED ISSUE #8091: homestead plugin do not show parsed commands
**Describe the bug**
Homestead plugin do not parse commands

**To Reproduce**
activate homestead plugin,
add shell function for homestead daily usage,
try print autocomplete commands - `homestead + <tab>`

**System:**
 - OS: 10.14.6
 - Zsh version zsh 5.7.1 (x86_64-apple-darwin18.2.0)
 - Terminal emulator default terminal 2.9.5 (421.2)
 - vagrant 2.2.5

**Additional context**
I create PR with fix this problem
https://github.com/robbyrussell/oh-my-zsh/pull/8008

### PR DESCRIPTION
**Pull request by pOmelchenko**
It's fix problem with empty list of commands

Fixes #8091

### CODE REVIEW

**Comment by mcornella** [comment]
Can you post the output of `homestead --no-ansi`?

**Comment by pOmelchenko** [comment]
```
➜  ~ homestead --no-ansi
Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     cloud           manages everything related to Vagrant Cloud
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     hostmanager     plugin: vagrant-hostmanager: manages the /etc/hosts file within a multi-machine environment
     init            initializes a new Vagrant environment by creating a Vagrantfile
     login           
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     port            displays information about guest port mappings
     powershell      connects to machine via powershell remoting
     provision       provisions the vagrant machine
     push            deploys code in this environment to a configured destination
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configuration
     resume          resume a suspended vagrant machine
     snapshot        manages snapshots: saving, restoring, etc.
     ssh             connects to machine via SSH
     ssh-config      outputs OpenSSH valid configuration to connect to the machine
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     upload          upload to machine via communicator
     validate        validates the Vagrantfile
     version         prints current and latest Vagrant version
     winrm           executes commands on a machine via WinRM
     winrm-config    outputs WinRM configuration to connect to the machine

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.

➜  ~ 
```

**Comment by pOmelchenko** [comment]
Ofcourse I can!

**Comment by mcornella** [comment]
Thanks!

**Pull request merged**
