### PR TITLE
gulp plugin: missing opening double quote

### PR DESCRIPTION
**Pull request by jcpst**
This plugin works properly now.

### CODE REVIEW

**Comment by nubs** [comment]
:+1: - this plugin is definitely broken without this fix.

**Comment by mcornella** [comment]
:+1: /cc @robbyrussell

**Comment by giordanovi** [comment]
There is a problem with the subtasks list. the plugin doesn't fetch the tasks with a : or . gulp.task("theme.assets", ....);
you can use a "gulp --tasks-simple" command to fetch the tasks list.

It's possible to implement this feature?

**Comment by vassyz** [comment]
Does it actually need double quotes?

**Comment by giordanovi** [comment]
No double quotes.
It should be something like this:
```
compls=$(gulp --tasks-simple >/dev/null | sort)
```

**Comment by mcornella** [comment]
@giordanovi that command looks much better, if you know how submit a PR and we'll test it. Thanks!

**Comment by giordanovi** [comment]
Hi @mcornella, 
sorry but i don't know how submit a PR. how can i do that?

**Comment by giordanovi** [comment]
I was able to submit the pull request! Thanks

**Pull request merged**
