### PR TITLE
The executable command on Mac OSX is 'ack' rather than 'ack-grep'.

### PR DESCRIPTION
**Pull request by hbin**
I have tested it on my Mac, and Ubuntu 14.04 in the virtual box.

### CODE REVIEW

**Comment by mcornella** [comment]
Hi @hbin, it's been a long time and since then we deleted the `lib/aliases.zsh` file and put the afind alias into `lib/misc.zsh`. Can you rebase your PR into the current master, and put the modified afind alias in misc.zsh?

**Comment by hbin** [comment]
Hi @mcornella, thanks for your message. I have rebased the PR, it's ready for merging now.

**Comment by mcornella** [comment]
:+1: /cc @robbyrussell

**Comment by CyberShadow** [comment]
I filed an issue against this addition, please see https://github.com/robbyrussell/oh-my-zsh/issues/5024

**Pull request merged**
