### PR TITLE
Spotify Controller

### PR DESCRIPTION
**Pull request by mahi97**
control Spotify by applescripts hooks and has search options with Spotify api for tracks, artists, albums and playlists.
also get information, share link and status about song that is playing.

### CODE REVIEW

**Comment by mahi97** [comment]
- There's some test of Spotify Controller

Spotify Basic Controls
[asciicast](https://asciinema.org/a/84452)

Spotify Extra options
[asciicast](https://asciinema.org/a/84454)

**Comment by robbyrussell** [comment]
Awesome! Seems to be working great for me. 

spotify in oh my zsh

**Comment by robbyrussell** [comment]
Dear @mahi97, it's come to our attention that the code that was contributed to this pull-request may be heavily inspired (maybe lifted) by @hnarayanan who has a Spotify via command line tool called [shpotify](https://github.com/hnarayanan/shpotify) ([compare the two](https://github.com/hnarayanan/shpotify/blob/59b51589e0070ff26395bc93b595e07725522a7b/spotify?utm_source=email&utm_content=2760115)).

The main concern is that if this was copied, we violated the copyright request in the original code. I'm working with @hnarayanan to sort out a good solution.

My assumption, @mahi97, is that you misunderstood the copyright/copy usage in the spirit of it being open source.

**Comment by mahi97** [comment]
Yes, the origin of this code is from @hnarayanan, that I just made a small change in it, at first I create a pull request for the shpotify repo but I guess the project was in the middle of a change [here](https://github.com/hnarayanan/shpotify/pull/46), and in the other hand after I saw Itunes plug-in in oh-my-zsh I've thought that moving my pull request from shpotify to this repo will be good help for a great amount of developers that currently using oh-my-zsh.
I'm really sorry for violating copyright, it was my very first contribution and I don't have enough knowledge to do it right.
Please tell me, If is there anything that I can/should do to help this situation.

**Comment by hnarayanan** [comment]
Thank you for acknowledging this. I understand that you were new to this process and weren’t aware of the specific copyright terms of the original project. 😊

You do not need to do anything, I have independently submitted a PR to this project that both updates the source code to a recent version and adds the relevant copyright permission notice.

Now that I know that this fork exists in the oh-my-zsh project, I will do my best to keep it up to date with the parent project. But you can definitely help with that in the future if you would like to!

**Comment by mahi97** [comment]
Thank you very much, I'll be so glad 😀

**Pull request merged**
