### PR TITLE
Added a light solarized theme for agnoster

### PR DESCRIPTION
**Pull request by questionmarc**
Made it so that there is a light solarized theme for agnoster. Should be a carbon copy of agnoster with color variants.

### CODE REVIEW

**Comment by mcornella** [comment]
Please add a screenshot and indicate what terminal emulator you use and which color scheme (if not the default).

**Comment by questionmarc** [comment]
Screen cap is here: http://imgur.com/SlOHNv7

The terminal emulator used is iTerm2 using a Solarized Light color scheme.

**Comment by apjanke** [comment]
Seems like a lot of duplicated code for a small change. Could this be done by adding an option and a bit of parameterization to the main `agnoster` theme?

**Comment by apjanke** [comment]
Looks like someones already done the parameterization, in #3434. It's added variables for setting all the colors, so you could piggyback off of that.

**Comment by mcornella** [comment]
Accounting for the changes in the agnoster theme since this PR was submitted, this only changes the instances of `black` for `white`. So I'm more inclined to making this an option within the current agnoster theme, like #4680 does. Sorry for the late reply.

----
Here's the clean diff:
```diff
diff --git a/themes/agnoster.zsh-theme b/themes/agnoster.zsh-theme
index 103041e..130e378 100644
--- a/themes/agnoster.zsh-theme
+++ b/themes/agnoster.zsh-theme
@@ -80,7 +80,7 @@ prompt_end() {
 # Context: user@hostname (who am I and where am I)
 prompt_context() {
   if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
-    prompt_segment black default "%(!.%{%F{yellow}%}.)$USER@%m"
+    prompt_segment white default "%(!.%{%F{yellow}%}.)$USER@%m"
   fi
 }
 
@@ -99,9 +99,9 @@ prompt_git() {
     dirty=$(parse_git_dirty)
     ref=$(git symbolic-ref HEAD 2> /dev/null) || ref="➦ $(git rev-parse --short HEAD 2> /dev/null)"
     if [[ -n $dirty ]]; then
-      prompt_segment yellow black
+      prompt_segment yellow white
     else
-      prompt_segment green black
+      prompt_segment green white
     fi
 
     if [[ -e "${repo_path}/BISECT_LOG" ]]; then
@@ -137,11 +137,11 @@ prompt_hg() {
         st='±'
       elif [[ -n $(hg prompt "{status|modified}") ]]; then
         # if any modification
-        prompt_segment yellow black
+        prompt_segment yellow white
         st='±'
       else
         # if working copy is clean
-        prompt_segment green black
+        prompt_segment green white
       fi
       echo -n $(hg prompt "☿ {rev}@{branch}") $st
     else
@@ -149,13 +149,13 @@ prompt_hg() {
       rev=$(hg id -n 2>/dev/null | sed 's/[^-0-9]//g')
       branch=$(hg id -b 2>/dev/null)
       if `hg st | grep -q "^\?"`; then
-        prompt_segment red black
+        prompt_segment red white
         st='±'
       elif `hg st | grep -q "^[MA]"`; then
-        prompt_segment yellow black
+        prompt_segment yellow white
         st='±'
       else
-        prompt_segment green black
+        prompt_segment green white
       fi
       echo -n "☿ $rev@$branch" $st
     fi
@@ -164,14 +164,14 @@ prompt_hg() {
 
 # Dir: current working directory
 prompt_dir() {
-  prompt_segment blue black '%~'
+  prompt_segment blue white '%~'
 }
 
 # Virtualenv: current working virtualenv
 prompt_virtualenv() {
   local virtualenv_path="$VIRTUAL_ENV"
   if [[ -n $virtualenv_path && -n $VIRTUAL_ENV_DISABLE_PROMPT ]]; then
-    prompt_segment blue black "(`basename $virtualenv_path`)"
+    prompt_segment blue white "(`basename $virtualenv_path`)"
   fi
 }
 
@@ -186,7 +186,7 @@ prompt_status() {
   [[ $UID -eq 0 ]] && symbols+="%{%F{yellow}%}⚡"
   [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}⚙"
 
-  [[ -n "$symbols" ]] && prompt_segment black default "$symbols"
+  [[ -n "$symbols" ]] && prompt_segment white default "$symbols"
 }
 
 ## Main prompt
```

**Pull request closed without merging**
