### PR TITLE
git: add pull rebase --autostash aliases

### PR DESCRIPTION
**Pull request by Poyoman39**
This is quite a nice feature from git. I'm not sure if it's better adding it to gup / gupv, or if it should be added to a new alias :)

### CODE REVIEW

**Comment by vrcca** [comment]
You read my mind! I was thinking about sending a PR to add `gupa` and `gupav`. The reason is that sometimes we want to make sure that we have a clean code tree, so making `gup` default to `--autostash` could cause some confusion. What do you think? 😄

**Comment by Poyoman39** [comment]
I totally agree with you 👍 After doing some gup --autostash i think a gupa would be really cleaner ! :P

**Comment by Poyoman39** [comment]
I just updated my pull request to do so :)

**Comment by emmanueltouzery** [comment]
this looks great, i hope this gets merged!

**Pull request merged**
