### PR TITLE
Added grho: git reset --hard origin/$(current_branch)

### PR DESCRIPTION
**Pull request by autodidacticon**

### CODE REVIEW

**Comment by vgaidarji** [comment]
+1

@autodidacticon You fixed typo in PR name but it remains in the commit message.

**Comment by autodidacticon** [comment]
@vgaidarji Good catch.

**Comment by vgaidarji** [comment]
I would vote for this feature +100 as probably I'm not the one who uses this command on daily basis.

**Comment by autodidacticon** [comment]
@ncanceill

**Comment by mcornella** [comment]
It's now `groh`.

**Pull request closed without merging**
