### PR TITLE
AWS plugin: alias for easier update of access keys

### PR DESCRIPTION
**Pull request by cristim**
This change initially included support for MFA authentication, which was later moved to a dedicated otp plugin.

Now it includes an alias for acces key updates and a few code style changes.

### CODE REVIEW

**Comment by ncanceill** [comment]
This still need more testers. @robbyrussell can we have the Testers Needed label on this?

**Comment by elias5000** [comment]
I use this on OSX 10.10.3. Works fine with a whole bunch of virtual MFAs.
(Also useful for google.com and any other service that uses Authenticator virtual MFA)

+1

**Comment by cristim** [comment]
@elias5000 now that you mention that, I'm thinking that perhaps it would make sense to move it into another plugin that just does MFA using oathtool

**Comment by cristim** [comment]
The MFA code was moved to a different plugin and submitted in the #3862 pull request.

I wouldrepurpose this pull request to only contain the key management part of the initial change

**Comment by mcornella** [comment]
I'd like to merge this one, can you rebase it?

**Comment by cristim** [comment]
Sure, I will look into this in the next few days

**Comment by mcornella** [comment]
Merged in https://github.com/robbyrussell/oh-my-zsh/commit/5f893dcd209fdad920a1450355acbd4c10faabf2. Thanks!

**Pull request closed without merging**
