### PR TITLE
Added plugin to delete a word forward like Alt+Backspace Reverse

### PR DESCRIPTION
**Pull request by VitorVRS**
I've create an plugin that allow you to use "Alt+Delete" to remove next word occurence on RBUFFER.
This works like "Alt+Backspace", but reverse.

### CODE REVIEW

**Comment by robbyrussell** [comment]
Can we get a README?

**Comment by VitorVRS** [comment]
Done

**Comment by notatestuser** [comment]
Doesn't seem to work on macOS.

**Comment by mcornella** [comment]
You can already do that with `kill-word`. In my system I have set up:
```zsh
# ALT + DEL deletes whole forward-word
bindkey '^[[3;3~' kill-word
# CTRL + DEL deletes whole forward-word
bindkey '^[[3;5~' kill-word
```

**Pull request closed without merging**
