### PR TITLE
 update rn plugin with ipad and apple tv sims

### PR DESCRIPTION
**Pull request by esthor**
just adding some more simulator aliases

### CODE REVIEW

**Comment by esthor** [comment]
@mcornella can you take a look? 😄

**Comment by mcornella** [comment]
I don't have macOS but I presume these strings work. Can you add the Apple TV ones to the README as well?

**Comment by esthor** [comment]
@mcornella nice catch, totally forgot to add them. Yeah, works on my system 🤷‍♀️ 😄

**Comment by mcornella** [comment]
👍

**Pull request merged**
