### PR TITLE
Update README.MD to fix invalid characters issue

### PR DESCRIPTION
**Pull request by pradeephrish**
A few invalid symbols in 'agnoster.zsh-theme' :
https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-275799694

this issue got introduced in 2013 and people are still confused and don't know right way to fix it.
It would be awesome if we can put this in README.md

Thanks & Regards,
Pradeep

### CODE REVIEW

**Comment by djsd123** [comment]
Nice one. 😀

I've only been using ITerm2 for a few hours but I thought the change fonts button was located at: `iTerm2 -> Preferences -> Profiles -> Text -> Change Font -> Family[12pt Meslo LG S DZ Regular for Powerline]` as opposed ro `iTerm2 -> Preferences -> Change Font -> 12pt Meslo LG S DZ Regular for Powerline`

**Comment by pradeephrish** [comment]
@djsd123 Thanks updated correct path

**Comment by jackerman1** [comment]
I am STILL having an issue after following these steps, where the carrot is misaligned with the rest of the block containing the path, and they are slightly different colors (OSX)
screen shot 2017-06-07 at 12 25 18 pm

Have you run into this?

**Comment by mcornella** [comment]
This is better suited in the wiki (FAQ section maybe).

**Pull request closed without merging**
