### PR TITLE
add cute and useful themes, https://github.com/Jyny/jyny.zsh-theme

### PR DESCRIPTION
**Pull request by Jyny**
add a cute and useful themes,
https://github.com/Jyny/jyny.zsh-theme

### CODE REVIEW

**Comment by Jyny** [comment]
A cute and useful themes,
https://github.com/Jyny/jyny.zsh-theme

**Comment by oshybystyi** [comment]
@Jyny next [page](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes) might change your attitude to your pr.

**Comment by ncanceill** [comment]
Indeed themes are [not accepted](https://github.com/robbyrussell/oh-my-zsh#do-not-send-us-themes).

@Jyny please follow the advice from @oshybystyi and list your theme in the list of external themes, and close this PR.

**Comment by Jyny** [comment]
I sorry about my pr.

**Comment by oshybystyi** [comment]
@Jyny - no worries. Maybe it looked mean, Sorry for that.

**Pull request closed without merging**
