### PR TITLE
Add new ZSH theme

### PR DESCRIPTION
**Pull request by gdsrosa**
Add this new improved minimal theme.  👍 🚀

### CODE REVIEW

**Comment by hjpotter92** [comment]
Check this section of readme: https://github.com/robbyrussell/oh-my-zsh#do-not-send-us-themes

**Comment by gdsrosa** [comment]
Oh @hjpotter92, I saw it, so how can I add this theme in External Theme?

**Comment by hjpotter92** [comment]
You can click the `edit` button on that page.

**Comment by gdsrosa** [comment]
Nice!! Does have any sequence pattern to put the new theme?

**Comment by hjpotter92** [comment]
Check page history :) https://github.com/robbyrussell/oh-my-zsh/wiki/Home/_history

**Comment by gdsrosa** [comment]
Thanks 😄, I made the change in history page.

**Pull request closed without merging**
