### PR TITLE
Added plugin and completion for sfdx

### LINKED ISSUE #7645: Support list of commands available for sfdx
Like SFDX is a lot of commands if you display next commands for parent display our life is easy.

Reference: https://github.com/wadewegner/salesforce-cli-zsh-completion

### PR DESCRIPTION
**Pull request by wadewegner**
This is a completion for the Salesforce CLI. I'm on the prod engineering team and it's quite useful.

Fixes #7645

### CODE REVIEW

**Comment by robbyrussell** [comment]
@wadewegner This looks great -- could you we do two things? 1. rename this to salesforcedx (as I think it'll help increase adoption from OMZ users as it'll be a recognizable name) and 2) add a README.md file with some usage examples?

Thanks in advance!

**Comment by chandra2ravi** [comment]
@wadewegner You completed below? and it's available?
could you we do two things? 1. rename this to salesforcedx (as I think it'll help increase adoption from OMZ users as it'll be a recognizable name) and 2) add a README.md file with some usage examples?

**Comment by mcornella** [comment]
I think `sfdx` is a good name for the plugin as long as it's popularly called that (the command is named the same way). Having a README is important though, see https://github.com/robbyrussell/oh-my-zsh/issues/7175#issue-365263634 for instructions on how to write a proper README for Oh My Zsh.

**Comment by rsoesemann** [comment]
@wadewegner looks like you are just a mini step away from getting merged ;-)

**Pull request merged**
