### PR TITLE
Renew terraform completions

### PR DESCRIPTION
**Pull request by ryosan-470**
See https://www.terraform.io/docs/commands/index.html#shell-tab-completion

I add generated `terraform -install-autocompletion` and remove old one.

### CODE REVIEW

**Comment by mhalano** [comment]
Why was this PR closed without merge? I just did a new PR that do the same thing.

**Comment by ryosan-470** [comment]
@mhalano I forgot why I closed this PR. Your contribution is great, thank you.

**Comment by carlosala** [comment]
It's merged in master! Thanks for your contribution!

**Comment by ryosan-470** [comment]
ok, thanks.

https://github.com/ohmyzsh/ohmyzsh/commit/fcbfdf42de702d55174fe2b19142ba232289671e

**Pull request closed without merging**
