### PR TITLE
Porting _adb from zsh-users/zsh-completions

### PR DESCRIPTION
**Pull request by zh0122**
Porting _adb from zsh-users/zsh-completions

### CODE REVIEW

**Comment by luca020400** [comment]
Great :+1:

**Comment by jgrar** [comment]
I don't know about this. Doing it this way won't track changes to zsh-users/zsh-completions, you've really just copied it out of that repository and into this one. It shouldn't be OMZ's responsibility to maintain someone else's work.

It would be a lot better for the user if they managed a repo that was seperate from OMZ *by themself* under custom/. Something like:

```
git clone https://github.com/zsh-users/zsh-completions.git
ln -s ./zsh-completions/src/_adb ~/.oh-my-zsh/custom/adb.zsh
```

**Comment by jgrar** [comment]
@zh0122 why did this get closed?

**Comment by zh0122** [comment]
Hi @jgrar ,

Because you said as below... 
> It shouldn't be OMZ's responsibility to maintain someone else's work.
It would be a lot better for the user if they managed a repo that was seperate from OMZ by themself under custom/, something like:

If you will merge it, I will reopen it

Thanks

**Pull request closed without merging**
