### PR TITLE
Added my theme called Numi

### PR DESCRIPTION
**Pull request by villimagg**
A simple and beautiful theme.
selection_009

### CODE REVIEW

**Comment by ncanceill** [comment]
Hi, and thanks for contributing.

However your contribution is [not acceptable](https://github.com/robbyrussell/oh-my-zsh#do-not-send-us-themes). Please be so kind as to close this PR and list your theme on the [appropriate wiki page](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes).

**Comment by KhasMek** [comment]
Per [#1899](https://github.com/robbyrussell/oh-my-zsh/pull/1899#issuecomment-29688978) and the [README](https://github.com/robbyrussell/oh-my-zsh/#do-not-send-us-themes) this project is no longer accepting PR's for new themes. If you'd like to add yours to the [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes) though, that'd be fantastic!

**Comment by ncanceill** [comment]
@KhasMek I am faster than my own shadow ;-)

**Comment by KhasMek** [comment]
@ncanceill I believe it! xD

**Pull request closed without merging**
