### PR TITLE
Update vundle plugin to latest Vundle.vim commands and repo name

### LINKED ISSUE #2794: vundle plugin - commands soon to be deprecated
The current vundle plugin uses the original `BundleInstall` commands from the older version of vundle.

The vundle project is undergoing some updates and among these are extra commands and new commands to replace the old ones. 

At a minimum any commands already used in this plugin should be changed to their replacement commands.

### PR DESCRIPTION
**Pull request by uberspot**
Fixes #2794

### CODE REVIEW

**Comment by nullsem** [comment]
Hi
I've tested these changes and they seem to work fine for me.

Thanks

**Comment by paulollivier** [comment]
Hi,
I tested it, works as it should.

Seems fine to me! :+1:

**Comment by ncanceill** [comment]
Thanks for testing guys.

@robbyrussell are you satisfied with this?

**Comment by mcornella** [comment]
This is fixed in the current version. Please close

**Pull request closed without merging**
