### PR TITLE
Setup `grep` alias lazily through a function

### PR DESCRIPTION
**Pull request by blueyed**
This saves an extra / initial call to `grep` during shell startup.

/cc @mcornella

### CODE REVIEW

**Comment by mcornella** [comment]
It doesn't work on first try though, what's the motivation of this?

**Comment by blueyed** [comment]
> It doesn't work on first try though

Fixed that.

I've also made it a function now, and auto-add `-r` if called on a dir. That might be too much magic though. What do you think?

**Comment by mcornella** [comment]
Yeah I'm not crazy about the recursive flag. Now at least it works all the time, but see that you removed the alias redefinition, so every time we run grep we'll be executing the setup function. 

Also, see my proposed PR where I turn grep into a function for further discussion regarding alias/function definition: #3347

**Comment by blueyed** [comment]
> but see that you removed the alias redefinition, so every time we run grep we'll be executing the setup function

It uses `unalias grep` and then sets up a function, when the alias is called for the first time.

This might also use the autoload mechanism provided by zsh, where the function would be defined in a file, which then gets sourced on the first invocation.

**Comment by mcornella** [comment]
Yeah sorry, I missed it. It's on the very [top of the function](https://github.com/robbyrussell/oh-my-zsh/pull/3474/files#diff-bfc27536871d24498f9e19c8e54b0628R22)

**Comment by mcornella** [comment]
Have you had a chance to look into the alias vs. function discussion? It was a little scattered into https://github.com/robbyrussell/oh-my-zsh/pull/3347#issuecomment-64924377 and https://github.com/robbyrussell/oh-my-zsh/pull/3341#issuecomment-64830311

**Pull request closed without merging**
