### PR TITLE
rvm plugin: Fix `gems` to work on Linux machine

### PR DESCRIPTION
**Pull request by yous**
Repeating the `-E` flag won't work with GNU sed.

### CODE REVIEW

**Comment by yous** [comment]
This pull request fixes #1579, which is not merged but closed by #2809, due to #1594, which fixed rbenv plugin.

**Comment by mcornella** [comment]
Huh, I could've sworn that #1579 and #1594 where the same thing. I see now that one fixed the `rbenv` plugin, and the other the `rvm` plugin.
Good to merge :+1: 
/cc @robbyrussell

**Comment by yous** [comment]
Any updates?

**Comment by yous** [comment]
Thanks!

**Pull request merged**
