### PR TITLE
Fixes Sublime Cygwin support

### LINKED ISSUE #4414: Sublime module parsing error.
sublime.plugin.zsh:43: parse error near `elif'

/Users/carlossuarezfontalvo/.oh-my-zsh/plugins/sublime/sublime.plugin.zsh:43: parse error near `elif'

```
➜  sublime git:(master) ✗ git diff sublime.plugin.zsh | cat
diff --git a/plugins/sublime/sublime.plugin.zsh b/plugins/sublime/sublime.plugin.zsh
index 62c6df8..f292195 100644
--- a/plugins/sublime/sublime.plugin.zsh
+++ b/plugins/sublime/sublime.plugin.zsh
@@ -38,7 +38,6 @@ elif  [[ "$OSTYPE" = darwin* ]]; then
             break
         fi
     done
-fi

 elif [[ "$OSTYPE" = 'cygwin' ]]; then
     local _sublime_cygwin_paths > /dev/null 2>&1
@@ -53,5 +52,6 @@ elif [[ "$OSTYPE" = 'cygwin' ]]; then
             break
         fi
     done
+fi
```

### PR DESCRIPTION
**Pull request by TylerCharlesworth**
@maxd is right! Copy/paste error initially.
https://github.com/robbyrussell/oh-my-zsh/pull/4396#commitcomment-13458853
Fixes #4414

### CODE REVIEW

**Comment by apjanke** [comment]
:+1:

@mcornella  and @robbyrussell, could we get this merged quickly? It's not just Cygwin support that's broken; the entire `sublime` plugin is currently broken because the syntax error prevents the plugin from running at all.

```
/Users/janke/.oh-my-zsh/plugins/sublime/sublime.plugin.zsh:43: parse error near `elif'
[~]
$ which st
st not found
[✘ ~]
$
```

**Comment by pfctgeorge** [comment]
:+1:

**Comment by apjanke** [comment]
Could you add a "Fixes #4414" to the main description of this PR so it auto-closes it?

**Comment by mguillermin** [comment]
:+1:

**Pull request merged**
