### PR TITLE
Updated autocomplete for Docker version 1.3

### PR DESCRIPTION
**Pull request by bobmaerten**
Docker has changed quite a lot since lastest update of this plugin.
And as @sanga resquested in #2803, I also was in huge need of containers name autocomplete.

### CODE REVIEW

**Comment by robbyrussell** [comment]
@bobmaerten Can you rebase this? Thanks in advance!

**Comment by bobmaerten** [comment]
Here it is, rebased from master.

**Comment by bobmaerten** [comment]
Here it is @robbyrussell, rebased from master.

**Comment by leifcr** [comment]
This should be closed in favor of #5060

**Comment by bobmaerten** [comment]
Small & quick commits/PR not quickly merged enough ends up like this. Glad to hand up to someone else.

**Comment by mcornella** [comment]
Sorry for the delay @bobmaerten!

**Pull request closed without merging**
