### PR TITLE
Alias gcamsg = git commit -a -m

### PR DESCRIPTION
**Pull request by ahfarmer**
I frequently use the `-a` flag but like to type my commit message inline, so I added `gcamsg`.

### CODE REVIEW

**Comment by blueyed** [comment]
You might be interested in my `gcm` and `gcma` aliases/functions:

    # Custom command modifier to not error on non-matches; similar to `noglob`.
    _nomatch () {
      setopt localoptions nonomatch
      local cmd=$1; shift
      # NOTE: not using 'command' to make it work with functions.
      # NOTE: quotes required with 'cmd foo: (bar)'
      # command $cmd ${~@}
      $cmd "${~@}"
    }
    compdef _precommand _nomatch

    # Helper: call a given command ($1) with (optional) files (popped from the
    # end).  This allows for "gcm 'commit message' file1 file2", but also just
    # "gcm message".
    command_with_files() {
      local cmd=$1; shift
      # Pop existing files/dirs from the end of args.
      files=()
      while (( $# > 1 )) && [[ -e $@[$#] ]]; do
        files+=($@[$#])
        shift -p
      done
      $=cmd "$*" $files
    }
    # Commit with message: no glob expansion and error on non-match.
    # gcm() { git commit -m "${(V)*}" }
    alias gcm='noglob _nomatch command_with_files "git commit -m"'
    # Amend directly (with message): no glob expansion and error on non-match.
    # gcma() { git commit --amend -m "${(V)*}" }
    # gcma() { git commit --amend -m "$*" }
    alias gcma='noglob _nomatch command_with_files "git commit --amend -m"'

([Source](https://github.com/blueyed/oh-my-zsh/blob/41dc664487f0822762e7fe9a69ca8102660cf525/plugins/git/git.plugin.zsh#L144-L164))

**Comment by ahfarmer** [comment]
Neither `gcm` nor `gcma` will commit files that I haven't manually added with `git add`, correct? I'm really looking for the combo of `--all`(`-a`) and `--message`(`-m`).

**Comment by blueyed** [comment]
Yes, but you could have a variant like `alias gcam='noglob _nomatch command_with_files "git commit -a -m"' then.  It just reminded me of my aliases, and I've thought you might like the extra niceties of these (if this suits your workflow).

**Comment by ahfarmer** [comment]
Ohhh. I get it. For me, adding a list of files that I want to `add` to the end of the `commit` command makes the command a little too big and un-wieldy. But I can see how other people would like it.

**Comment by jvz** [comment]
This is equivalent to using `gcma "message" -v` I think.

**Comment by ahfarmer** [comment]
Plenty of other options here - thanks guys! Closing this PR.

**Pull request closed without merging**
