### PR TITLE
Add zsh completion plugin for rustc

### PR DESCRIPTION
**Pull request by scialex**
This is taken from my PR for rustc (https://github.com/rust-lang/rust/pull/17306), which is getting merged once the CI system is fixed.

### CODE REVIEW

**Comment by jansegre** [comment]
Any news on this?
I'm setting it up manually but would be much more pleased if it were available on oh-my-zsh.

**Comment by andradei** [comment]
+1 to have this available.

Right now I'm using [antigen](https://github.com/zsh-users/antigen) and getting a rust plugin from the [official rust repo](https://github.com/rust-lang/zsh-config)

Maybe a PR over there and antigen would be a nice setup.
Or you guys can make a repo with your plugin and we can use antigen to pull it directly from your repo.

Just a few options.

**Comment by orhanbalci** [comment]
Any update on this PR. Since Rust gained some more attention more developers would benefit from this.

**Comment by andradei** [comment]
This project should be an organization with more people having the ability to accept PRs like this.

ping @robbyrussell

**Comment by mcornella** [comment]
Sorry for the delay people!

**Pull request merged**
