### PR TITLE
compdef: unknown command or service

### PR DESCRIPTION
**Pull request by magicalbanana**
Commented line should eliminate this error until fix is found or proper investigation is made.

### CODE REVIEW

**Comment by Kriechi** [comment]
@magicalbanana you mean a proper investigation by searching through existing issues on GitHub?
https://github.com/robbyrussell/oh-my-zsh/issues/2337#issuecomment-38144387

Please close this PR.

**Comment by apjanke** [comment]
Instead of merging this PR, I'd try to diagnose and fix the issue on the machine(s) where you're getting it.

The error `compdef: unknown command or service` occurs if you call `compdef` before initializing the zsh completion system by calling `autoload -U compinit; compinit`. Normally the `oh-my-zsh.sh` file will do this for you as part of oh-my-zsh startup. It's at [line 62](https://github.com/robbyrussell/oh-my-zsh/blob/bf7b9165fd725d2bdf45ca7e639b2c91f5ef65bb/oh-my-zsh.sh#L62-L64).

This could be caused by a messed-up `oh-my-zsh.sh`. Or a bad `.zcompdump` file. Try deleting your zcompdump files with `rm ~/.zcompdump*` and using `git` to check that your oh-my-zsh install is up to date and doesn't have any local changes, and then try again.

If you're still getting the error, you can smooth over it by patching `plugins/rails/rails.plugin.zsh` in your `$ZSH_CUSTOM` directory instead of disabling it for all OMZ users.

**Comment by apjanke** [comment]
Sorry, I misread the error message: it's `command not found` that happens when `compinit` hasn't run; this looks like it's coming from `compdef` itself. I still think it's worth trying to diagnose and fix, or disabling via `$ZSH_CUSTOM` before doing a PR to turn it off globally.

**Comment by ncanceill** [comment]
@magicalbanana this issue probably occurs because the version of Zsh you are running does no support completion for rails. Please upgrade your Zsh distribution.

**Comment by ncanceill** [comment]
... and please keep in mind that arbitrarily commenting out a line printing an error does not make said error go away.

**Comment by apjanke** [comment]
Is this issue still happening for you?

**Pull request closed without merging**
