### PR TITLE
Add Readme for sbt

### PR DESCRIPTION
**Pull request by mzuehlke**
This adds a readme file for the sbt plugin as requested in #7175

### CODE REVIEW

**Comment by MasterOfTheTiger** [comment]
The tables need to be fixed.

**Comment by mzuehlke** [comment]
Fixed the table rendering by shortening the description text.

**Comment by MasterOfTheTiger** [comment]
It looks good for now. Someone will look at it later.

**Comment by mcornella** [comment]
Great, thanks!

**Pull request merged**
