### PR TITLE
Patch for detect shell file in Solus OS

### PR DESCRIPTION
**Pull request by frbuceta**
Patch for install Oh-My-Zsh in Solus

### CODE REVIEW

**Comment by chikamichi** [comment]
Cool patch, but actually you may workaround this by running `sudo chsh -s /bin/zsh [username]` where the username is mandatory and expected to be yours of course. Which means it's just a matter of editing install instructions over at Oh-My-Zsh's wiki I guess :)

**Comment by chikamichi** [comment]
At the same it's true that this missing /etc/shells binding does affect script-install, not just manual install, so OMZ might be better off fixing the issue in the install script.

**Comment by frbuceta** [comment]
Perfect :) I would love to see it working perfectly Oh My Zsh by Solus Os

**Comment by mcornella** [comment]
Hey there, I pulled this change in #5169 and it's now ready to test (I pulled other fixes and features).

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!

**Comment by mcornella** [comment]
Closed by #5169.

**Pull request closed without merging**
