### PR TITLE
add virualenv prompt info into pygmalion

### PR DESCRIPTION
**Pull request by Shellbye**
since pygmalion has no virualenv prompt info, so I added it.

### CODE REVIEW

**Comment by NerdsvilleCEO** [comment]
Any updates on this? This would be helpful

**Comment by kwiersma** [comment]
Would be great to see this one included. Thanks!

**Comment by stephencoe** [comment]
2 years later and I land here looking for this same functionality :(

**Comment by Daemoen** [comment]
Yep....  why hasnt this been merged?

**Pull request merged**
