### PR TITLE
Search for Gulp tasks in more locations

### PR DESCRIPTION
**Pull request by adam-beck**
Searches for tasks in the following locations: gulpfile.js, gulpfile.babel.js, and gulp directory of a project.

### CODE REVIEW

**Comment by apjanke** [comment]
I think that `gulp/*.js` can end up producing a `zsh: no matches found: gulp/*.js` error message, even though stderr from `grep` is sent to /dev/null. Might want to use `gulp/*.js(N)` to allow it to silently produce an empty result set when there are no matches.

**Comment by apjanke** [comment]
The `$compls` and `$completions` variables look like they should be `local`, too. Could that be fixed while you're in here?

**Comment by apjanke** [comment]
This conflicts with #4487 and #4463. Can these be reconciled so we only have one outstanding PR for it?

**Comment by adam-beck** [comment]
#4463 would make #4487 and it (#4463) does check for tasks inside of `gulpfile.babel.js` files. Therefore, this commit is obsolete as well. I would make your comments on #4463.

**Pull request closed without merging**
