### PR TITLE
Added auto-completion for external commands.

### PR DESCRIPTION
**Pull request by mhalano**
Fixes #3456 
Following Nicolas idea I create a pull request for add rehash support, but using a branch so he can add code to create a option to enable/disable rehash.

### CODE REVIEW

**Comment by ncanceill** [comment]
PR submitted.

**Comment by mhalano** [comment]
PR merged.

**Comment by ncanceill** [comment]
Outstanding!

This PR looks ready to me, but it would be good to find a few more people to support it.

**Comment by mcornella** [comment]
I've been running with this setup in my zshrc file since December 30th of last year and I haven't had any problems nor noticed any significant delays. :+1:

**Comment by ncanceill** [comment]
What is the status of this?

**Comment by mhalano** [comment]
I created another PR just to add a zstyle line in a good place.

**Pull request closed without merging**
