### PR TITLE
Added README for mercurial plugin

### PR DESCRIPTION
**Pull request by oshybystyi**

### CODE REVIEW

**Comment by ncanceill** [comment]
Thanks!

Would you be so kind as to update the [wiki entry](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#mercurial) too?

Also please list @ptrv as the maintainer — along with yourself if you wish.

**Comment by oshybystyi** [comment]
@ncanceill added maintainers and updated wiki (https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#mercurial)

**Comment by ncanceill** [comment]
Nice! Can you squash your commits in order to keep the history clean and atomic?

**Comment by oshybystyi** [comment]
@ncanceill, done

**Comment by ncanceill** [comment]
Outstanding!

**Pull request closed without merging**
