### PR TITLE
Recognize comments by default.

### LINKED ISSUE #3385: Comment is not recognized
Please, skip this message for commands starting with #
zsh: command not found: #

### PR DESCRIPTION
**Pull request by tejasbubane**
Fixes #3385 
PR against #3432

### CODE REVIEW

**Comment by mcornella** [comment]
Ok cool, it's works for me.
/cc @robbyrussell

**Comment by robbyrussell** [comment]
Can you quickly rebase this for me?

**Comment by tejasbubane** [comment]
@robbyrussell Done.

**Comment by ncanceill** [comment]
:+1: 

@robbyrussell please pull in this easy merge.

**Comment by tejasbubane** [comment]
@robbyrussell please merge this. I accidentally ran into this error today when I pasted some snippet with comment and zsh threw an error at me. Was expecting this to be already merged.

**Comment by ncanceill** [comment]
This will be merged in #3809.

**Pull request closed without merging**
