### PR TITLE
[plugins/git] Updated git clone alias

### PR DESCRIPTION
**Pull request by kkalavantavanich**
`git clone --recursive` has been deprecated in favor of `--recurse-submodules`.  
Also added `-j8` to speed up clone.
See: https://stackoverflow.com/questions/3796927

### CODE REVIEW

**Comment by steelrooter** [comment]
👍

**Comment by kkalavantavanich** [comment]
@mcornella So what do you suggest then: `--recurse-submodules` or `--recursive`, or both?

**Comment by mcornella** [comment]
I think `--recurse-submodules` is ok, just lose the `-j8`.

**Comment by kkalavantavanich** [comment]
Done

**Comment by mcornella** [comment]
Thanks!

**Pull request merged**
