### PR TITLE
Update Mix completion upto 1.0.4

### PR DESCRIPTION
**Pull request by styx**

### CODE REVIEW

**Comment by styx** [comment]
:up:

**Comment by ncanceill** [comment]
Hi @styx could you please rebase?

**Comment by styx** [comment]
@ncanceill done

**Comment by ncanceill** [comment]
Thanks.

**Comment by styx** [comment]
Just updated complition upto 1.0.4

**Comment by styx** [comment]
@robbyrussell, sorry for disturbing you this way, I know there is tons of PRs. Would you be so kind to take a look at this patch and merge it? It is very simple update. Thanks :heart: :yellow_heart: :green_heart: :purple_heart: !

**Comment by mcornella** [comment]
This will be merged once #3809 is merged, which will be really soon.

**Pull request closed without merging**
