### PR TITLE
Print out current revision with grev

### PR DESCRIPTION
**Pull request by zackhsi**
```bash
➜  grev git:(master) grev
62efe2c72c40eede2cadbd08b5b4b58cf8b19443
```

### CODE REVIEW

**Comment by zackhsi** [comment]
@mcornella ?

**Comment by mcornella** [comment]
Can you comment on an instance when that command is necessary / helpful?

**Comment by zackhsi** [comment]
Alice: "Bob, is your branch up to date?"
Bob: "One sec, let me see ... _checks the output of `grev`_ ... Yep, I'm running 1a2b3c, pulling now."

**Comment by mcornella** [comment]
I'm not convinced. A simple `git show` or `git log` would do, and if you use it that much that you need this I don't think anyone else will benefit because you still have to remember another alias.
Thanks!

**Pull request closed without merging**
