### PR TITLE
disable composer xdebug warning for autocomplete

### PR DESCRIPTION
**Pull request by koenpunt**
see composer/composer#4622

### CODE REVIEW

**Comment by mcornella** [comment]
Sorry, I merged #4676 instead. Thanks!

**Comment by koenpunt** [comment]
Oh well, `COMPOSER_DISABLE_XDEBUG_WARN` is probably the recommended way.. Because other errors that may arise are now suppressed as well

**Comment by mcornella** [comment]
That's what I thought, but off the top of my head I only recall having seen errors about composer version being too old, which are not relevant when requesting for completion entries (it will show anyway after running whatever command it autocompleted).

I see [in this page](https://getcomposer.org/doc/articles/troubleshooting.md) that this is not exactly true ―there are other possible errors―, but let's go with the whole stderr approach and see what happens. In case any of those errors is triggered, the completion function should just return nothing, and a subsequent `composer diagnose` would show the whole trouble.

**Comment by koenpunt** [comment]
If for any reason you consider to merge my changes, I've rebased my branch on current master :)

**Comment by mcornella** [comment]
Ok thanks, if anything comes up I'll use this one. Thank *you* :smile:

**Pull request closed without merging**
