### PR TITLE
Fix checkmark for clean repo in bureau theme

### PR DESCRIPTION
**Pull request by isqua**
The checkmark in clean repo wasn’t dispalyed. Now it fixed.

### CODE REVIEW

**Comment by isquariel** [comment]
I’ve just rebase the branch from master.

**Comment by mcornella** [comment]
[Cleaner diff](https://github.com/robbyrussell/oh-my-zsh/pull/2752/files?w=0), for reference. 

Can you go a little further and turn those grep calls into `command grep`? That way we bypass the grep alias.

**Comment by isquariel** [comment]
I’ve replaced grep with `command grep`, thanks for issue.

**Comment by zoobestik** [comment]
:+1:

**Comment by edubskiy** [comment]
:+1:

**Comment by mtnbikenc** [comment]
This change seems to have broken the logic for reporting 'clean' repos.  Still testing, but at least when a repo is 'ahead', it still shows the checkmark for 'clean'.

**Comment by mcornella** [comment]
Yes, sorry, I'm aware of it and working on a PR. I'll let you know when it's fixed.

**Comment by mcornella** [comment]
@mtnbikenc please have a look at #4976.

**Pull request merged**
