### PR TITLE
Fixed atom plugin for cygwin users

### PR DESCRIPTION
**Pull request by rams3s**

### CODE REVIEW

**Comment by wsdjeg** [comment]
thank you

来自我的华为手机

-------- 原始邮件 --------
主题：[oh-my-zsh] Fixed atom plugin for cygwin users (#4349)
发件人：rams3s
收件人：robbyrussell/oh-my-zsh
抄送：


You can view, comment on, or merge this pull request online at:

  https://github.com/robbyrussell/oh-my-zsh/pull/4349

-- Commit Summary --

  * Fixed atom plugin for cygwin users

-- File Changes --

    M plugins/atom/atom.plugin.zsh (38)

-- Patch Links --

https://github.com/robbyrussell/oh-my-zsh/pull/4349.patch
https://github.com/robbyrussell/oh-my-zsh/pull/4349.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/robbyrussell/oh-my-zsh/pull/4349

**Comment by mcornella** [comment]
:+1: but use `$OSTYPE` instead of running `uname`.

**Comment by rams3s** [comment]
Thanks for the tip @mcornella

**Comment by mcornella** [comment]
Great! :+1: 
/cc @robbyrussell

**Comment by mcornella** [comment]
Hey, a quick addition before we merge this: could you add back the `att` alias as well (see [this comment](https://github.com/robbyrussell/oh-my-zsh/commit/953e4d892631f93e31cfdfb72199fb8f413c6b49#commitcomment-13393648)).

**Pull request merged**
