### PR TITLE
Fix gbda alias to support `color.ui = always` + exclude dev branches

### PR DESCRIPTION
**Pull request by cmalard**
The alias `gbda` actually doesn't work if `git config color.ui = always`.
Some invisible characters are included in branch names wich causes the following :
- master branch is not excluded
- on deletion, the output is : `error: branch 'x' not found.` And there is no deletion at all.

The `--no-color` option solves this problem.

Also, `command` seems unnecessary.

I excluded `develop` and `dev` branches to make it usable with Git Flow. Should I do this in another PR or is it ok to keep it here ?

### CODE REVIEW

**Comment by cmalard** [comment]
@mcornella : why `new` ? This is an update of an existing alias.

What should I do to accelerate the merge process ? :-)

**Comment by mcornella** [comment]
I did some bulk-labeling so this one must have marked new by mistake. The `command` part is to ignore aliases or functions named `grep` and run the command directly, if you readd that I'll merge this right away.

**Comment by mcornella** [comment]
The branch exclusion of `develop` and `dev` is fine.

**Comment by cmalard** [comment]
`command` is back and I simplified the RegEx :-)

**Comment by mcornella** [comment]
Perfect! :+1:

**Pull request merged**
