### PR TITLE
Add argument to set644 and set755 perms alias.

### PR DESCRIPTION
**Pull request by ardeidae**
This can avoid big mistakes as this I just made.
I thought I could give it an argument. So, now, it is possible.

### CODE REVIEW

**Comment by mcornella** [comment]
No need to rename the functions, just use `set644` and `set755` and you can get rid of the aliases.

**Comment by ardeidae** [comment]
@mcornella, this is fixed. I didn't know how to modify my pull request...

**Comment by ardeidae** [comment]
I've changed to accept any number of arguments. Readme updated too.
Is it ok for you?

**Comment by mcornella** [comment]
Thanks!

**Pull request merged**
