### PR TITLE
Zsh Navigation Tools plugin

### PR DESCRIPTION
**Pull request by psprint**
Hello,
I've written these:

https://github.com/psprint/zsh-navigation-tools

There are screenshots and videos about the tools on the page. They can work as OMZ plugin, can you please include them. They are very thoroughly tested and optimized.

Best regards,
Sebastian Gniazdowski

### CODE REVIEW

**Comment by robbyrussell** [comment]
Could you include a README file, too?

**Comment by psprint** [comment]
Yes, I added it

**Comment by psprint** [comment]
Hello I've overwritten the plugin with latest version

**Comment by psprint** [comment]
Hello, I've once again overwritten the plugin with most recent version

**Comment by psprint** [comment]
Hello,
what's with the merge?

**Comment by apjanke** [comment]
This project says it's GPL, but Oh My Zsh is MIT licensed, which is incompatible. Could ZNT be dual-licensed under MIT, too?

I'm going to give these a spin.

**Comment by apjanke** [comment]
How do the `.config` files fit in with ZNT when using it as an OMZ plugin? Is it up to the user to create `~/.config/znt` themselves using the files in the upstream repo?

**Comment by apjanke** [comment]
I have a couple suggestions for changes. I'll submit them upstream; let's sort them out there before merging this in to OMZ.

**Comment by psprint** [comment]
Hello,
I've overwritten PR with new version of ZNT. Followed apjanke advice to utilize the fact that fpath is being set to plugin directory. Many other fixes applied, prepared customized README.txt, clarified the situation with configuration files. One of easily visible effects of loading the plugin is having n-history bound to ^R. Could you merge?

**Comment by psprint** [comment]
Hello,
how it will be with the merge? It's a really mature project now, should be zero bugs, and the multi-word history search is a nice thing to have. Could you merge?

Best regards,
Sebastian Gniazdowski

**Comment by psprint** [comment]
Thanks for the merge!

**Pull request merged**
