### PR TITLE
Added plugin for Visual Studio Code

### PR DESCRIPTION
**Pull request by wyldphyre**
Added a plugin to enable triggering Visual Studio Code from the command line. Nothing fancy.

p.s. Not sure why the changes from Feb 2015 are included here. I thought they'd already been merged. I've rebased from the original, but I'm not that hot with Git, so not sure what's going on there.

### CODE REVIEW

**Comment by Kriechi** [comment]
Can you please remove the Atom file and squash your commits?
As far as I can tell this only works for OSX at the moment, can you maybe add support for linux?
You can take a look at other plugins (e.g. Atom, Sublime Text, etc.)

**Comment by wyldphyre** [comment]
I don't know how to remove files from the pull request. I wouldn' have included them in the first place if I could have seen a way to avoid it.

I'd rather not add support for stuff I can't test.

**Comment by wyldphyre** [comment]
I'm going to close this pull request and start over with a fresh fork. Will try to support platforms other than OS X when I do.

**Comment by Kriechi** [comment]
@wyldphyre: take a look at this function: 
https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/functions.zsh#L18

And for the file: just remove it, commit your changes and then squash all commits.

**Comment by wyldphyre** [comment]
Repository is gone now. Will do it again at some point.

**Comment by wyldphyre** [comment]
oh, forgot to say, thanks for pointing me to open_command.

**Pull request closed without merging**
