### PR TITLE
Add README.md for dirhistory plugin

### PR DESCRIPTION
**Pull request by MasterOfTheTiger**
This adds a readme file for the dirhistory plugin as requested in #7175.

### CODE REVIEW

**Comment by mcornella** [comment]
Beautifully done \*chef's kiss\*

**Comment by MasterOfTheTiger** [comment]
Thanks. I will see about adding READMEs to other plugins as well. Do you have any other recommendations for contributions I could work on @mcornella?

**Comment by mcornella** [comment]
Well we always need people to test and review PRs, the [testers needed label](https://github.com/robbyrussell/oh-my-zsh/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3A%22testers+needed%22) is full of them (there are ancient ones, you can skip those). And mostly work on things you know well, such as plugins for things you regularly use.


I really should put this suggestion somewhere more public...

**Comment by MasterOfTheTiger** [comment]
How old is ancient? And there does not seem to be too many new ones.

**Pull request merged**
