### PR TITLE
add plugin to support `please build system`

### PR DESCRIPTION
**Pull request by chpeer**
Add plugin for the please build system.

### CODE REVIEW

**Comment by mcornella** [comment]
Has no interest.

**Comment by janhancic** [comment]
@mcornella why was this closed? Especially since the work was already done.

This would be a very welcome improvement, I use please every day and would love support for it in oh-my-zsh.

**Comment by mcornella** [comment]
When I closed it it had zero comments or +1s, making it a good candidate for closure out of the 100+ new plugins submitted. Somehow closing it has brought it to the attention of users, but I can't reopen it now because the branch has been deleted.

**Comment by janhancic** [comment]
I don't think the branch has gone anywhere. Worst case @chpeer can raise a new PR :+1:

**Comment by mcornella** [comment]
Added in ebc700be9b2fa7ae770a644093a5c46a8e323726. I had to fetch the PR from the terminal.

**Pull request closed without merging**
