### PR TITLE
Plugin to magically escape zsh meta-characters in git commands

### PR DESCRIPTION
**Pull request by pho3nixf1re**
The plugin simply autoloads git-escape-magic which is included here and
copied from https://github.com/knu/zsh-git-escape-magic .

This addresses #1115

### CODE REVIEW

**Comment by Konfekt** [comment]
Looks convenient. How about taking aliases of `git` into account, like `g` ? Could this not serve as a general escape-magic plugin ? For example `zcalc` also would be handier if `*` is auto escaped.

**Comment by Konfekt** [comment]
Never mind. Just found out at

http://stackoverflow.com/questions/11456403/stop-shell-wildcard-character-expansion/22945024#22945024

about `alias g='noglob git'`

**Comment by Konfekt** [comment]
Any comments on why this has not been merged? This is a convenient plugin for users of zsh and git  that otherwise needs manual fiddling to install.

**Comment by mcornella** [comment]
I thought there wasn't any more interest in this plugin.

**Comment by pho3nixf1re** [comment]
I am still interested in this. I have it in the custom plugins folder currently and have used it since this was opened.

**Comment by mcornella** [comment]
Ok, I'll gladly merge this. Can you add a README with instructions on how to use it (for instance, that it doesn't work with git aliases) and update to the latest version of the git-escape-magic file?

**Comment by pho3nixf1re** [comment]
Sure, I'll get to be by the end of the week. Thanks!

**Comment by pho3nixf1re** [comment]
I'm cleaning house on my old PR's. I just updated this with a README and updated the script. I have also verified that this plugin still works. If there are no other concerns it should be ready for merge now. Thanks for the insane patience on this!

**Comment by pho3nixf1re** [comment]
Just pinging on this, I'm still using it myself and I'm sure others would like to have access to it. Anything left to get it merged?

**Comment by mcornella** [comment]
Congratulations on being probably the oldest PR merged (sorry)

**Pull request merged**
