### PR TITLE
fzf: Adding support for debian packages

### PR DESCRIPTION
**Pull request by gorsil**
Added function to setup fzf from deb package. Separated everything into functions, for clarity

### CODE REVIEW

**Comment by gorsil** [comment]
https://github.com/robbyrussell/oh-my-zsh/issues/7998

**Comment by gorsil** [comment]
@maxbrunet You are right, I overlooked that detail.
Added fix for that.

**Comment by Jerome1337** [comment]
Any news on the ETA of this fix?

**Comment by mcornella** [comment]
Thanks @gorsil!

**Pull request merged**
