### PR TITLE
Agnoster: solarized light variant

### PR DESCRIPTION
**Pull request by fcrozat**
This pull request allows a light variant of agnoster theme, to be used with Solarized light theme.

### CODE REVIEW

**Comment by mcornella** [comment]
Sorry for the late reply, can you please post a screenshot with the solarized light color schema?

**Comment by fcrozat** [comment]
capture d ecran de 2016-03-30 10-21-33
This is a screenshot : first line is without the fix applied and second line with the fix applied..

**Comment by fcrozat** [comment]
sorry, better screenshot attached
capture d ecran de 2016-03-30 10-30-44

**Comment by fcrozat** [comment]
Screenshot, when solarized light is in effect (visible mostly on the prompt) 
capture d ecran de 2016-03-30 10-30-44

Prompt (first line without fix, second line with fix)
capture d ecran de 2016-03-30 10-21-33

**Comment by fcrozat** [comment]
Is there anything blocking the merge of this pull request ?

**Comment by gbrlsnchs** [comment]
Any updates on this? It's been some time since the opening of this pull request...

**Comment by dydokamil** [comment]
Where do I set the SOLARIZED_THEME variable? I tried in Linux, .Xresources, .zshrc and in the theme itself, but does not work.

**Comment by peacetara** [comment]
Any chance of a merge?

**Comment by mcornella** [comment]
Thanks!

**Pull request merged**
