### PR TITLE
Add alias for checking out develop branch

### PR DESCRIPTION
**Pull request by mastersimon**

### CODE REVIEW

**Comment by mcornella** [comment]
Are you using git-flow? If so, there's a dedicated plugin for that.

**Comment by mastersimon** [comment]
Hey,
I´m not using git-flow.

**Comment by mcornella** [comment]
:+1:

**Comment by kaHaleMaKai** [comment]
That commit introduced a bug into my zsh: I cannot use any git related commands anymore. They just don't print anything. When reverting the commit, it works correct again.

on master branch:
`kauai :: ~/.oh-my-zsh % gst`
`kauai :: ~/.oh-my-zsh %`

after reverting the commit:
`kauai :: ~/.oh-my-zsh ‹without-b9c3e862› % gst`
`On branch without-b9c3e862`
`nothing to commit, working tree clean`

**specs:**
* ubuntu 14.04.5
* zsh 5.0.2
* plugins: git command-not-found gitfast git-extras lein pip python screen ssh-agent sublime urltoos emacs-mode web-search wd

Please tell me if you need anything else.

**Comment by mcornella** [comment]
Can you post the content of `$ZSH/plugins/git/git.plugin.zsh` on master?

**Comment by kaHaleMaKai** [comment]
Sure. I have attached the file with the extensions txt, so I could upload it (.zsh was prohibited).

[git.plugin.zsh.txt](https://github.com/robbyrussell/oh-my-zsh/files/455295/git.plugin.zsh.txt)

**Comment by mcornella** [comment]
I see nothing wrong with it. Please open a new issue and post your zshrc and the output of `git show without-b9c3e862` in the OMZ folder.

**Comment by kaHaleMaKai** [comment]
Thanks for taking the time to investigate that further!

By chance, I just found the problem: I had defined an alias `gcd` like ages ago, but in that very commit the same alias has been defined, but with another meaning. If I remove the custom alias from my .zshrc, it runs smoothly again.

**Pull request merged**
