### PR TITLE
added a transfer.sh plugin

### PR DESCRIPTION
**Pull request by ilyes-kechidi**
Created a  single function to easily upload files to [transfer.sh](transfer.sh) file sharing site
Usage : `$ transfer file.txt`

### CODE REVIEW

**Comment by slavaGanzin** [comment]
transfer.sh is great, but you should separate formatusb into another PR

**Comment by ilyes-kechidi** [comment]
Hello , I made a mistake working pushing to the master branch :/
how can i seperate the commits to different branches ? im not that good with git , sorry

**Comment by slavaGanzin** [comment]
```
git checkout master #checkout to master from which we will create new branch
git reset --hard 0b340bc3a5c58609a07987b296f773eaea17b274 #switch master before your changes
git checkout -b transfer #create new branch
git cherry-pick 	a488561 #add commit related to this branch
#Add plugins/transfer/Readme.md

#same for another branch
git checkout master
git checkout -b formatusb
git cherry-pick fc7bd5d
#Add plugins/formatusb/Readme.md
```

After that create two separate PR

**Comment by slavaGanzin** [comment]
https://gist.github.com/nl5887/a511f172d3fb3cd0e42d

But I think this is better to PR

**Comment by ilyes-kechidi** [comment]
I made the changes to another pr https://github.com/robbyrussell/oh-my-zsh/pull/5854

Yes it's better it can upload zipped directories

Should i PR his code instead ??

**Comment by slavaGanzin** [comment]
> Should i PR his code instead ??
Yes

**Pull request closed without merging**
