### PR TITLE
Add omz_diagnostic_dump() to help with bug reporting

### LINKED ISSUE #3915: Diagnostic dump function for bug reporting?
Hi, OMZ folks,

A lot of the issues we get are problem reports about OMZ on a particular user's machine, and since there's complex configuration for both the system and OMZ, we end up doing a lot of back and forth to elicit more info from the user. I think it would make bug reports easier if we had a function in OMZ that would just dump out all the relevant state and configuration for OMZ and ZSH, so the user could just submit that instead of answering a series of questions in comments.

I've put one together at [diagnostics.zsh](https://github.com/apjanke/oh-my-zsh-custom/blob/master/diagnostics.zsh) in my oh-my-zsh-custom tree. It dumps out information about the user's system and shells, zsh and environment state, OMZ installation, and grabs copies of all the relevant zsh configuration files.

Any interest in bringing this in to the main OMZ distribution, maybe as `lib/diagnostics.zsh`?

### PR DESCRIPTION
**Pull request by apjanke**
This adds a new `lib/diagnostics.zsh` library file for OMZ/ZSH diagnostic functions, and defines the `omz_diagnostic_dump()` function that will dump a lot of info about the user's current shell state and configuration files to a dump file suitable for posting as a gist.

The intention is that this could be made part of the normal debugging and support workflow by asking bug reporters to just "run `omz_diagnostic_dump()` and post the results" instead of having to ask a series of questions and request individual files.

I've been using this in my custom dir for a while and it's been helpful with diagnosing some issue reports already (#3913, #3356, #3724, #3350).

Closes #3915

### CODE REVIEW

**Comment by mcornella** [comment]
One more thing: set the locale to default so that everything is in English. I achieved that through `local -x LC_ALL=C`, which is the same as `local LC_ALL=C; export LC_ALL` that you did in #4129.

**Comment by apjanke** [comment]
That's probably a good idea. I'll look at how to structure that: it's a little tricky since this function runs in the same shell session that it's examining, and part of the output is to capture the user's existing `locale` settings. And we'd want any command or file resolution etc that could be affected by locale settings to be done under the user's locale so we can see what they're seeing.

**Comment by mcornella** [comment]
Oh, right. Hadn't thought of that. In my test run this only happened in the `grep` version output, but version number was totally readable after all. On further thought, I don't think there's a necessity to do that.

In `systeminfo`, however, the output in spanish doesn't have `OS Name/OS Version` but since it's the very first thing that's printed you can get it with `systeminfo | head -n 4 | tail -n 2`.

Finally, in Linux and cygwin as I have checked, `md5sum` is generally available so you can try that if `md5` is not found.

**Comment by apjanke** [comment]
Ah, I didn't know that about `systeminfo`. Would `LC_ALL` even fix that? `systeminfo` is a native Windows command, not a Cygwin one, so I don't know that it would respect Unix style locale variables.

**Comment by apjanke** [comment]
How about `shasum`? That seems pretty widely available, and then we don't have to worry about the interface differences between `md5` and `md5sum`.

Switched the `systeminfo` output filtering to your line-based method.

**Comment by mcornella** [comment]
> Ah, I didn't know that about systeminfo. Would LC_ALL even fix that? systeminfo is a native Windows command, not a Cygwin one, so I don't know that it would respect Unix style locale variables.

That's exactly right, forgot to add that but I see you thought about it anyway :smile:

It's perfect now, I think it's ok to merge :+1:
/cc @robbyrussell

**Comment by apjanke** [comment]
Thanks!

**Comment by robbyrussell** [comment]
Thanks @apjanke !

**Comment by apjanke** [comment]
You're welcome! Thanks for getting this merged.

**Pull request merged**
