### PR TITLE
Replace spotify command in the osx plugin with a more recent copy of the upstream project

### PR DESCRIPTION
**Pull request by hnarayanan**
## Description

This pull request replaces the existing `spotify` command in the osx plugin with a more featured script from https://github.com/hnarayanan/shpotify. The motivation for this can be seen in an earlier discussion: https://github.com/robbyrussell/oh-my-zsh/pull/5356#issuecomment-344048908

In addition to simply replacing the code, it improves the script such that it can search using the new Spotify API that requires authentication.

Closes: #6118, https://github.com/hnarayanan/shpotify/issues/84
Makes redundant: #6170, #6232, #6345, #6291

## Specific changes

- Removes the old spotify function and replaces it with a copy from the upstream project (now as a separate file). I have separated it out to make it easier for me to keep it up-to-date with the upstream project.
- Includes this file using `source`. Not sure if this is a blessed thing to do.
- Adds the original project's copyright permission as an acknowledgement in this plugin's README.

I am open to discussion and improving how these changes are implemented. I have just submitted a simple, functional implementation. 😅 

cc: @robbyrussell

### CODE REVIEW

**Comment by hnarayanan** [comment]
@mahi97: You could probably help test this to get it merged.

**Comment by itacos** [comment]
Thanks @hnarayanan  it works for me 👍 

```
cd ~/.oh-my-zsh
wget https://github.com/robbyrussell/oh-my-zsh/pull/6419.patch
git am 6419.patch

spotify play artist the doors

Connecting to Spotify's API
Searching artists for: the doors
play uri: spotify:artist:22WZ7M8sxp5THdruNY3gXt
Playing (the doors Search) -> Spotify URI: spotify:artist:22WZ7M8sxp5THdruNY3gXt
```

**Comment by hnarayanan** [comment]
Could others please help test this so it can be merged? 🙏 :smile_cat:

**Comment by felipeauol** [comment]
@hnarayanan Merged this in and after adding my API credentials it now works for me as well. Thank you! 👍

**Comment by hnarayanan** [comment]
👍

**Comment by felipeauol** [comment]
So trying more commands I noticed searching by artist does not trigger playing the artist even though it finds the correct URI:

`
spotify play artist Sia
Connecting to Spotify's API
Searching artists for: Sia
play uri: spotify:artist:5WUlDfRSoLAfcVSX1WnrxN
Playing (Sia Search) -> Spotify URI: spotify:artist:5WUlDfRSoLAfcVSX1WnrxN
`

Searching by list also does not seem to ever find any results. 

`
spotify play list mood booster      
Searching playlists for: mood booster
No results when searching for mood booster
`

Search by album works fine though.

**Comment by hnarayanan** [comment]
1. Playing by artist works for me.

```
[~] spotify play artist kanye west
Connecting to Spotify's API
Searching artists for: kanye west
play uri: spotify:artist:5K4W6rqBFWDnAN6FQUkS6x
Playing (kanye west Search) -> Spotify URI: spotify:artist:5K4W6rqBFWDnAN6FQUkS6x
```

At which point the Spotify opens up with the artist's most popular song.

screen shot 2017-12-02 at 4 46 04 pm

2. The interface for the list search has changed and is not working as you've noticed. Please report this in the parent project (https://github.com/hnarayanan/shpotify) and someone who uses this feature will likely fix it.

**Comment by BerniWittmann** [comment]
I can also confirm, that playing by artist works for me, but playing by list is still broken (apparently it's already fixed in the parent project (https://github.com/hnarayanan/shpotify)).

**Comment by hnarayanan** [comment]
List play has been fixed in the parent project. I will merge the fix into this PR shortly.

**Comment by hnarayanan** [comment]
I have merged in the most recent version of `shpotify` that fixes playing by list.

**Comment by hnarayanan** [comment]
Thank you!

**Pull request merged**
