### PR TITLE
Add Google Flutter auto-completion plugin

### PR DESCRIPTION
**Pull request by sashko**

### CODE REVIEW

**Comment by febs** [comment]
How do I install this manually?
Thanks

**Comment by sashko** [comment]
@febs you just copy file to `~/.oh-my-zsh/plugins/`

**Comment by sashko** [comment]
Updated plugin for Flutter 0.8.2.

**Comment by mcornella** [comment]
Wait, I was going to merge it, but there's a richer completion file over at [zsh-completions](https://github.com/zsh-users/zsh-completions/blob/master/src/_flutter), I highly recommend using that instead. Thanks for your contribution!

**Pull request closed without merging**
