### PR TITLE
New plugin for the n98-magerun Magento command line tool

### PR DESCRIPTION
**Pull request by andrew-dwyer**
This is a new completion plugin for the n98-magerun tool for Magento.  https://github.com/netz98/n98-magerun

### CODE REVIEW

**Comment by cmuench** [comment]
@andrew-dwyer Works on Ubuntu 14.04 on my machine.

**Comment by mwr** [comment]
+1

**Comment by ncanceill** [comment]
@andrew-dwyer were you able to fix @byymster's issue?

**Comment by andrew-dwyer** [comment]
Hi @byymster, I've included your fix. Apparently some implementations of awk don't support \s.
@cmuench @mwr @mattias Could you please test the latest fix? I've also added file completion

**Comment by DavidLambauer** [comment]
+1 !!

**Comment by tkn98** [comment]
+1

**Comment by c-walter** [comment]
+1

**Comment by cmuench** [comment]
+1

**Comment by rlieser** [comment]
+1

**Comment by ycelik** [comment]
+1

**Comment by jissereitsma** [comment]
+1

**Comment by aleron75** [comment]
+1

**Comment by WouterSteen** [comment]
+1

**Comment by steverobbins** [comment]
+1

**Comment by michaellehmkuhl** [comment]
+1

**Comment by byymster** [comment]
+1

**Pull request merged**
