### PR TITLE
Fix to make the gitstatus.py works with any language

### PR DESCRIPTION
**Pull request by c4software**
Hi,

The script fail when the language of the system is not set at "en_US.UTF-8" . I have made change to force the lang to en_US.UTF-8 when this script run.

I also notice the behead_re and  diverge_re regexp are wrong. (extra # and space at the begining)

Now the gitstatus.py return the correct informations.

### CODE REVIEW

**Comment by c4software** [comment]
Anyone can review it?

**Comment by mcornella** [comment]
A better way would be using `LANG=en_US.utf8` before python in [line 46 of `git-prompt.plugin.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git-prompt/git-prompt.plugin.zsh#L46).
Can you test that out?

A better language, though, would be using `C`, which picks the default language in which git is written (in this case, English). In some systems, mainly those that are in languages other than English, "en_US" locale is not available.

**Comment by c4software** [comment]
Nop its doesn't work.

**Comment by mcornella** [comment]
Sorry, I meant to say `C.utf8`, can you try it out? Also, post the output of `locale -a`

**Comment by mcornella** [comment]
Updates @c4software ?

**Comment by mcornella** [comment]
Ok, I finally reviewed this and it seems to be worse than expected. Let's pull in the latest changes from [olivierverdier/zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt) instead.

**Comment by mcornella** [comment]
My recent PR #4205 solves this problem, as well as the `#` regexps.

**Comment by c4software** [comment]
Thanks for the feedback (sorry for the delay…)

**Comment by mcornella** [comment]
No problem! Do you mind checking #4205 and +1 there if it works?

**Pull request closed without merging**
