### PR TITLE
Add plugin for Visual Studio Code

### PR DESCRIPTION
**Pull request by wyldphyre**
Confirmed it works on OS X. Theoretically will work on Linux and Windows, but I've not been able to test it.

### CODE REVIEW

**Comment by TuiKiken** [comment]
Merge please

**Comment by hinaloe** [comment]
:+1:

**Comment by chuyik** [comment]
Can't this be merged?

**Comment by mcornella** [comment]
Visual Studio Code already provides a `code` command, I don't see the need to have a plugin that overwrites the default behavior. See [the setup instructions](https://code.visualstudio.com/Docs/editor/setup) for more info.

**Comment by funkyLover** [comment]
after the shell command install
run `code .` to open current folder with vscode
run `code package.json` to open specific file with vscode
also you can add alias in `~/.zshrc` like
```
alias -s html=code
alias -s md=code
alias js=code
alias css=code
```
and then you can just type `index.html`, the vscode will open index.html direct
all above try in OSX

**Comment by mcornella** [comment]
Ok I'm closing this since it works well on OSX without this plugin enabled. See https://github.com/robbyrussell/oh-my-zsh/pull/4650#issuecomment-208748043 and [setup instructions](https://code.visualstudio.com/Docs/editor/setup) for more info!

**Pull request closed without merging**
