### PR TITLE
Include dotfiles in TAB completion

### PR DESCRIPTION
**Pull request by nmaggioni**
Includes hidden files and folders in ```TAB``` key completion.

### CODE REVIEW

**Comment by apjanke** [comment]
This seems more like a personal preference that should be left up to to the individual user to turn on if they want it.

**Comment by nmaggioni** [comment]
In my opinion the vast majority of users would want this, and the documentation to enable this feature is quite hard to find on the web...

**Comment by dragonxlwang** [comment]
+1, hope user can have a toggle function to enable showing hidden files

**Comment by mcornella** [comment]
I agree with @apjanke on this one. This is more like a user preference, and enabling it is as easy as adding that same line to your zshrc file:
```zsh
# Enable hidden files completion
_comp_options+=(globdots)
```

**Pull request closed without merging**
