### PR TITLE
Added gmail in websearch plugin

### PR DESCRIPTION
**Pull request by junipdewan**
Added Gmail in web search plugin

Tagging @iamantu93 @mcornella could you guys please take a look?

### CODE REVIEW

**Comment by junipdewan** [comment]
Tagging @iamantu93

**Comment by junipdewan** [comment]
@mcornella  I have resolved the conflicts, can you please merge it?

**Comment by mcornella** [comment]
As I said in #7680, the purpose of the plugin is to allow easy access to search engines, not any website that has search capabilities.

**Comment by junipdewan** [comment]
thanks @mcornella

**Pull request closed without merging**
