### PR TITLE
"Zsh not installed" fix #6796

### LINKED ISSUE #6796: Zsh is not installed! Please install zsh first!
hello robbyrusell !

after install like your description on debian 9.4 i got this error:

Zsh is not installed! Please install zsh first!

zsh is install

```
# /etc/shells: valid login shells
/bin/sh
/bin/dash
/bin/bash
/bin/rbash
/bin/zsh
/usr/bin/zsh
```

two hours ago i install it on a another debian 9.4 computer and it works and i see you make changes one hour ago

please fix

### PR DESCRIPTION
**Pull request by mriedmann**
Quick fix for #6796

### CODE REVIEW

**Comment by CryDeTaan** [comment]
How about this?
`if ! hash zsh 2>/dev/null; then
    printf "${YELLOW}Zsh is not installed!${NORMAL} Please install zsh first!\n"
    exit
  fi`

**Comment by mriedmann** [comment]
@CryDeTaan also completely valid.

Just to clarify: The `hash` solution was present in line 50 and got replaced with this (see https://github.com/robbyrussell/oh-my-zsh/commit/4fec0a46e73479cf3b9e7f953750af5ed5df87ac#diff-55b046be8e081f97f37b7667e1c4bfa9):
```
printf "${BLUE}Cloning Oh My Zsh...${NORMAL}\n"
  command -v git >/dev/null 2>&1 || {
    echo "Error: git is not installed"
    exit 1
  }
```
so I used the "or side-effect" approach. There is already a (closed) PR for this solution: #6798

**Comment by adambullmer** [comment]
Any reason you don't just add as `!` to the existing check? Just looks like a simple case of inverted logic to me.

```bash
if ! command -v zsh >/dev/null 2>&1; then
# ...
```

**Comment by mriedmann** [comment]
As I sad, I just wanted to provide a concise solution (because this solution was replaced at another line earlier). A simpler fix (the one you suggested) can be found in PR #6798

**Pull request closed without merging**
