### PR TITLE
README.md: shit load -> shit-load

### PR DESCRIPTION
**Pull request by eli-b**

### CODE REVIEW

**Comment by duggiefresh** [comment]
[I think this `shitload` is the accepted spelling.](https://www.merriam-webster.com/dictionary/shitload)

**Comment by eli-b** [comment]
I updated to shitload.

**Comment by eli-b** [comment]
Also, @duggiefresh, I think 'Assistant' is the accepted spelling regarding your GitHub bio :)

**Comment by duggiefresh** [comment]
Hahaha @eli-b, that's great. Thanks for the 👀 !

**Comment by eli-b** [comment]
I always tell my friends it's part of my job to be a pedant :)

בתאריך יום ג׳, 24 באוק׳ 2017, 19:25, מאת Doug Yun ‏<notifications@github.com

**Comment by robbyrussell** [comment]
💩

**Pull request merged**
