### PR TITLE
Fix repeated omz_history event not found error message

### LINKED ISSUE #6754: omz_history:fc:15: event not found: -l
I have a problem here after PR #3422 has been merged. When I type any command in Terminal, it says `omz_history:fc:15: event not found: -l`. I also added `unsetopt hist_verify` to `.zshrc`

### PR DESCRIPTION
**Pull request by dkramer95**
Fixes #6754

### CODE REVIEW

**Comment by mcornella** [comment]
When does this work? I've tested the function for 2 years and I've never had an error like that. How are you calling `history` that makes it throw the error?

**Comment by mcornella** [comment]
Yeah but the question is why. Let me see what `print -l $precmd_functions $preexec_functions` shows.

**Comment by mcornella** [comment]
And the output of `typeset -ft omz_history`.

**Comment by dkramer95** [comment]
### Before #6755

```
print -l $precmd_functions $preexec_functions
+omz_history:3> zparseopts -E 'c=clear' 'l=list'
+omz_history:5> [[ -n '' ]]
+omz_history:9> [[ -n '' ]]
+omz_history:15> fc -l 1 53
omz_termsupport_precmd
steeef_precmd
omz_termsupport_preexec
steeef_preexec
```

```
typeset -ft omz_history
+omz_history:3> zparseopts -E 'c=clear' 'l=list'
+omz_history:5> [[ -n '' ]]
+omz_history:9> [[ -n '' ]]
+omz_history:15> fc -l 1 54
```


### After #6755
```
print -l $precmd_functions $preexec_functions
omz_termsupport_precmd
steeef_precmd
omz_termsupport_preexec
steeef_preexec
```

```
typeset -ft omz_history
```

**Comment by mcornella** [comment]
Ok, so that's an incorrect use of the `history` builtin by the steeef theme. #6359 will fix it.

**Comment by mcornella** [comment]
Merged. You can now update.

**Pull request closed without merging**
