### PR TITLE
Tugboat plugin

### PR DESCRIPTION
**Pull request by DimitriSteyaert**
This is my autocompletion plugin for the tugboat (https://github.com/pearkes/tugboat) tool to manage Digital Ocean droplets.

### CODE REVIEW

**Comment by DimitriSteyaert** [comment]
Hi @oryband, I'm sorry but I lost track of your EC2 request. I've taken a look at it but there seems to be a large list of EC2 commands, each with their own command parameters (http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/command-reference.html). As I can't keep track of every command and parameter that changes I am keeping my hands of this :). This seems to be a task for Amazon themselves.

**Comment by oryband** [comment]
:(

**Comment by ncanceill** [comment]
Hi, and thanks for contributing.

Could you please squash your commits so I can add this to #3809?

**Comment by DimitriSteyaert** [comment]
Hi @ncanceill 
commits have been squashed.

**Comment by ncanceill** [comment]
Thanks. Remember to update the [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins) when #3809 gets merged.

**Comment by oryband** [comment]
@avivl @fuzzyami

**Comment by ncanceill** [comment]
@DimitriSteyaert this is now merged into master, please update the wiki page.

**Comment by DimitriSteyaert** [comment]
@ncanceill Wiki has been updated.

**Comment by ncanceill** [comment]
Are you sure you properly saved your changes? They currently do not show up.

**Comment by DimitriSteyaert** [comment]
Oh I only edited the plugins overview page, sorry. The plugins page has also been updated now.

**Comment by ncanceill** [comment]
Excellent!

**Pull request closed without merging**
