### PR TITLE
Support for 'scw' command (Scaleway CLI)

### PR DESCRIPTION
**Pull request by moul**
Adds autocomplete options for all [scw](https://github.com/scaleway/scaleway-cli): Manage Bare Metal servers from Command Line (as easily as with Docker) commands.

### CODE REVIEW

**Comment by ncanceill** [comment]
Impressive job!

You will now have to find people to test and +1 this.

**Comment by QuentinPerez** [comment]
:+1:  😊

**Comment by aimxhaisse** [comment]
Works like a charm :+1:

**Pull request merged**
