### PR TITLE
use https everywhere

### PR DESCRIPTION
**Pull request by YoshiMan**

### CODE REVIEW

**Comment by ojongerius** [comment]
Nice work! Did you verify those urls support https too?

**Comment by YoshiMan** [comment]
I have looked for http urls with the following command.
`grep -R http:// oh-my-zsh/plugins/  --include='*.zsh`
Then I changed the _http_ to _https_ and checked the url with the browser.
There have been some cases
- no response even on the http version -> I changed nothing
- no response -> I changed nothing
- invalid certificate -> I changed nothing
- mixed content -> I changed to https
- everything ok -> I changed to https

**Comment by YoshiMan** [comment]
Hey @ojongerius,
did you read my response? What do you think about my pull request?
I wrote an email to the guy who has the website with the mixed content. :)

**Comment by ojongerius** [comment]
@YoshiMan I did, thanks for going the extra mile!

I don't have write permissions to this repository, so not the person to convince this is a good thing. Just trying to chime in and make sure this PR is good to merge when a collaborator or owner comes along and has a look.

**Comment by YoshiMan** [comment]
Ah okay. Thanks a lot.
I hope this pullrequest wont be dead like #6484 and #6485

**Comment by ojongerius** [comment]
Same! Seems like there is more work than hands in regards to code review and merges.

**Comment by mcornella** [comment]
I've updated the PR with the rest of http links that could be changed and got rid of broken links in the process. This is now ready to merge. Thanks for getting the ball rolling!

Just a few days after the [Chrome change](https://www.blog.google/products/chrome/milestone-chrome-security-marking-http-not-secure/)! :)

**Comment by YoshiMan** [comment]
Yeah thank you :+1:

**Pull request merged**
