### PR TITLE
Add Fedora support for command-not-found plugin

### LINKED ISSUE #3482: Fedora support for command-not-found plugin
Fedora 21 has command not found behaviour for bash. But this plugin didn’t work in Fedora.

/cc @toctan @lorrin @sargas

### PR DESCRIPTION
**Pull request by ai**
Fedora support by comment from [this issue](https://bugzilla.redhat.com/show_bug.cgi?id=678934) to close #3482.

/cc @robbyrussell

### CODE REVIEW

**Comment by ai** [comment]
@robbyrussell how I can with this PR? :)

**Comment by mcornella** [comment]
This is an identical copy of the solution provided in [this comment](https://bugzilla.redhat.com/show_bug.cgi?id=678934#c0) in @ai's linked issue, so I don't think it needs any more proof.
/cc @robbyrussell: good to go! :+1:

**Comment by ai** [comment]
@robbyrussell any updates :)

**Comment by ai** [comment]
@robbyrussell what is block this PR for merge?

**Comment by mcornella** [comment]
Hi @ai, we'll get this merged soon.

**Pull request merged**
