### PR TITLE
add IntelliJ IDEA plugin

### PR DESCRIPTION
**Pull request by dozer47528**
like the atom plugin, this plugin can open Intellij IDEA project from shell.

just use:

`idea .` or `idea /projects/test_project`

### CODE REVIEW

**Comment by robbyrussell** [comment]
Can you include a README file?

**Comment by dozer47528** [comment]
@robbyrussell 
done!

**Comment by Xerus2000** [comment]
what happened to this PR?

**Comment by hoshsadiq** [comment]
@Xerus2000 I don't know what happened to this PR however, you don't need this. You can simply create a idea cli script through the interface. IIRC it's in Tools > Create command line launcher

**Pull request closed without merging**
