### PR TITLE
Add --all flag to brew update command

### PR DESCRIPTION
**Pull request by robertd**

### CODE REVIEW

**Comment by Kriechi** [comment]
Thanks - I think we already got like 42 PRs fixing this very same thing.
The most promising one would be #3809 (@ncanceill)

**Comment by mcornella** [comment]
This will be fixed when #3809, which will be imminent. I'm adding it to #3651.

**Comment by DomT4** [comment]
You may wish to hold off on that for now. Reversal is under discussion in https://github.com/Homebrew/homebrew/pull/40372.

**Comment by mcornella** [comment]
You're absolutely right. Let's make sure that's not pushed then: https://github.com/Homebrew/homebrew/commit/a45a34db0b2c66f626f3724ae9a52563b4aa94b5

**Comment by robertd** [comment]
Looks like they reverted it. Closing the issue.

**Comment by mcornella** [comment]
Thanks @robertd and @DomT4

**Pull request closed without merging**
