### PR TITLE
Pacaur aliases in the Arch Linux plugin

### PR DESCRIPTION
**Pull request by DoctorJellyface**
[Pacaur](https://wiki.archlinux.org/index.php/Pacaur) is another AUR helper, though arguable one of the more popular ones. I (obv) use it too, and I missed aliases a lot, so I made them myself.

It's basically the same as the Yaourt/Pacman aliases. I tested every command I included. I also documented all my changes.

Hope you like it.

### CODE REVIEW

**Comment by DoctorJellyface** [comment]
Forgot that the pacaur aliases wouldn't work if yaourt was installed, fixed it.

**Comment by Ramsdenj** [comment]
I'd like to see this in main.

**Comment by mcornella** [comment]
I'm sorry I forgot about this one. I'll close it and push #5460 which doesn't have conflicts, but I'll make sure to pull in your commits as well to make your contributions count.

Sorry again!

**Comment by mcornella** [comment]
Pushed to master. Thanks again!

**Pull request closed without merging**
