### PR TITLE
Add rubocop to bundled_commands

### PR DESCRIPTION
**Pull request by flanger001**
Exactly what it says on the tin! Rubocop is a great addition to the `bundled_commands` list. This was already done in https://github.com/robbyrussell/oh-my-zsh/pull/3199 but that PR didn't get merged because of an issue with `berks`.

### CODE REVIEW

**Comment by flanger001** [comment]
@mcornella Not sure who else to tag here, so I'm tagging you!

**Comment by flanger001** [comment]
Bumpity bump.

**Comment by mcornella** [comment]
I'm not familiar enough with bundler nor rubocop to know if it should be bundled by default. The [rubocop project](https://github.com/rubocop-hq/rubocop#installation) mentions it can be either bundled or not... Why not just use [`BUNDLED_COMMANDS`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/bundler/README.md#add-additional-gems-to-be-wrapped)?

**Comment by flanger001** [comment]
Well, 2 things:

1. `BUNDLED_COMMANDS` would be fine for my purposes and it's my bad I didn't look at it first.
2. The argument I'd make in favor of including it in this list is rubocop is pretty damn near a standard gem these days. It's in more projects than [some](https://github.com/search?utf8=%E2%9C%93&q=%22gem+annotate%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [of](https://github.com/search?utf8=%E2%9C%93&q=%22gem+cap%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [the](https://github.com/search?utf8=%E2%9C%93&q=%22gem+capify%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [gems](https://github.com/search?utf8=%E2%9C%93&q=%22gem+cucumber%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [already](https://github.com/search?utf8=%E2%9C%93&q=%22gem+foodcritic%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [in](https://github.com/search?utf8=%E2%9C%93&q=%22gem+hanami%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [the](https://github.com/search?utf8=%E2%9C%93&q=%22gem+irb%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [list](https://github.com/search?utf8=%E2%9C%93&q=%22gem+kitchen%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=), [actually](https://github.com/search?utf8=%E2%9C%93&q=%22gem+knife%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [most](https://github.com/search?utf8=%E2%9C%93&q=%22gem+middleman%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [of](https://github.com/search?utf8=%E2%9C%93&q=%22gem+nanoc%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [them](https://github.com/search?utf8=%E2%9C%93&q=%22gem+rackup%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [if](https://github.com/search?utf8=%E2%9C%93&q=%22gem+rainbows%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [I](https://github.com/search?utf8=%E2%9C%93&q=%22gem+shotgun%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [am](https://github.com/search?utf8=%E2%9C%93&q=%22gem+sidekiq%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [being](https://github.com/search?utf8=%E2%9C%93&q=%22gem+spec%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [honest](https://github.com/search?utf8=%E2%9C%93&q=%22gem+spork%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=). [Take](https://github.com/search?utf8=%E2%9C%93&q=%22gem+strainer%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [it](https://github.com/search?utf8=%E2%9C%93&q=%22gem+tailor%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [for](https://github.com/search?utf8=%E2%9C%93&q=%22gem+taps%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [what](https://github.com/search?utf8=%E2%9C%93&q=%22gem+thin%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [you](https://github.com/search?utf8=%E2%9C%93&q=%22gem+thor%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=) [will](https://github.com/search?utf8=%E2%9C%93&q=%22gem+unicorn_rails%22+filename%3AGemfile&type=Code&ref=advsearch&l=&l=), but I think it would be a slam dunk.

**Comment by mcornella** [comment]
You certainly did your research there 😄 

Tell me something though, what potential errors can happen if someone runs rubocop normally outside of bundler and it is run bundled next time? I've also seen some Gemfiles [don't have the `require: false` parameter](https://github.com/renuo/micro_cms/blob/5ab0f50a405a854aab955b3b713624081191c557/Gemfile#L17), does that affect something?

**Comment by flanger001** [comment]
Haha, I actually triggered an abuse detection mechanism for Github doing that!

1. I don't believe any errors can happen in the situation you described, nor any change in behavior. I think errors could occur if rubocop was installed globally (i.e. `gem install rubocop`) but not in a project, then run bundled.
2. Normally bundler automatically requires all gems in a Gemfile. `require: false` prevents bundler from requiring the gem and makes the user manually add `require "gem_name"` to use it in application code.  Some gems really hate being required automatically, but I've worked in many projects where the Gemfile didn't have `require: false` for rubocop in it and I'd be remiss if I said I noticed a difference.

**Comment by mcornella** [comment]
Fair enough, can you update the README to indicate rubocop is bundled as well?

**Comment by flanger001** [comment]
> Fair enough, can you update the README to indicate rubocop is bundled as well?

Done. Do you want this rebased against upstream?

**Comment by mcornella** [comment]
Thanks 👍

**Comment by flanger001** [comment]
Thank you @mcornella!

**Pull request merged**
