### PR TITLE
Update docker completion to match docker upstream

### PR DESCRIPTION
**Pull request by cpuguy83**
See
https://github.com/docker/docker/blob/master/contrib/completion/zsh/_docker

### CODE REVIEW

**Comment by cpuguy83** [comment]
I'll update this with the latest from upstream.
This is quite outdated now.

**Comment by cpuguy83** [comment]
Excellent, looks like this was pulled in already.
PR will just update to docker 1.12.1 completion.

**Comment by mcornella** [comment]
Thanks!

**Comment by leifcr** [comment]
@mcornella Thanks!

**Pull request merged**
