### PR TITLE
Add aliases scu-* for 'systemctl --user' commands

### PR DESCRIPTION
**Pull request by sumitsahrawat**

### CODE REVIEW

**Comment by robbyrussell** [comment]
@sumitsahrawat Thanks -- are the last three lines duplicated for a reason?

**Comment by sumitsahrawat** [comment]
I have never personally used the `--now` flag, so I just added aliases passing it (`scu-enable-now` etc, notice the *u*) by copying the ones that pass it currently (`sc-enable-now` etc).

>

**Comment by sumitsahrawat** [comment]
> are the last three lines duplicated for a reason?

I have never personally used the `--now` flag, so I just copied the aliases that use it currently:

```
alias sc-enable-now="sc-enable --now"
alias sc-disable-now="sc-disable --now" 
alias sc-mask-now="sc-mask --now"
```

And added new ones that pass both `--now` and `--user` to systemctl:

<pre>
alias sc<b>u</b>-enable-now="sc<b>u</b>-enable --now"
alias sc<b>u</b>-disable-now="sc<b>u</b>-disable --now" 
alias sc<b>u</b>-mask-now="sc<b>u</b>-mask --now"
</pre>

> Thanks

It's an extreme pleasure to be making a contribution to `oh-my-zsh` 👍 ❤️

**Comment by sumitsahrawat** [comment]
This PR looks ready to be merged.

Would help get me out of situations like this:

```zsh
$ sc-restart emacs # doesn't work
$ sc-restart --user emacs # still doesn't work
$ systemctl restart --user emacs # finally it works
```

**Pull request merged**
