### PR TITLE
Add hanami plugin inspired by rails plugin

### PR DESCRIPTION
**Pull request by iBublik**
For deatils visit http://hanamirb.org/guides/command-line/applications/

### CODE REVIEW

**Comment by robbyrussell** [comment]
Hi there, thanks for this. Could you provide a README file in this directory, too?

**Comment by iBublik** [comment]
@robbyrussell done!

**Comment by mcornella** [comment]
Could you add a list of the aliases as a table in your README? Have a look at the xcode plugin README for an example.

**Comment by iBublik** [comment]
@mcornella sure, here it is

**Comment by mcornella** [comment]
Sorry for the long wait!

**Pull request closed without merging**
