### PR TITLE
Remove docker insert command

### PR DESCRIPTION
**Pull request by waynelkh**
"docker insert command" has been removed.

### CODE REVIEW

**Comment by ncanceill** [comment]
Looks fine to me.

CC @ aeonazaan @ bobmaerten @bergvandenp

(When you want to contribute to a plugin, please CC the maintainer(s) when applicable.)

**Comment by bobmaerten** [comment]
:+1:

**Comment by ncanceill** [comment]
OK thanks @bobmaerten.

@waynelkh I want to add this to #3809 but your fork seems unavailable. Care to submit the same PR to [my branch](https://github.com/ncanceill/oh-my-zsh/tree/easymerge)?

**Comment by waynelkh** [comment]
@ncanceill I had submit a PR to you repo
Please check it, thanks!

**Pull request closed without merging**
