### PR TITLE
added a transfer.sh plugin

### PR DESCRIPTION
**Pull request by ilyes-kechidi**
Created a single function to easily upload files to transfer.sh file sharing site
Usage : $ transfer file.txt
@slavaGanzin

### CODE REVIEW

**Comment by slavaGanzin** [comment]
@ilyes-kechidi Would you change this PR to add ziping directories?

**Comment by ilyes-kechidi** [comment]
Done @slavaGanzin

**Comment by slavaGanzin** [comment]
@ilyes-kechidi
I tested it. Works as expected.

I think we should switch to ```tar czf``` from zip, because tar is by default on all linux systems and zip is optional.

**Comment by ilyes-kechidi** [comment]
@slavaGanzin 
Working on it

**Comment by ilyes-kechidi** [comment]
Done @slavaGanzin
needs testing though :)

**Pull request merged**
