### PR TITLE
Create random emoji theme emoji.zsh-theme

### PR DESCRIPTION
**Pull request by audy**
You're probably sick of new themes. But not this theme.

A different emoji for every prompt.
Inspired by http://www.hardscrabble.net/2013/random-emoji-in-prompt/

### CODE REVIEW

**Comment by oshybystyi** [comment]
If github had a viote functionality - I would vote against.

I prefer creating a separate wiki page and linking to it from [here](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#dont-send-us-your-theme-for-now).

This wiki page could contain images of additional themes with installing instructions pointing to [here](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes)

**Comment by ncanceill** [comment]
This is cute but [not acceptable](https://github.com/robbyrussell/oh-my-zsh#do-not-send-us-themes), sorry.

**Comment by audy** [comment]
@oshybystyi are you suggesting I put the theme on the wiki and link to the source/instructions elsewhere? @ncanceill maybe can we have a separate wiki page for external themes?

**Comment by oshybystyi** [comment]
@audy you understand my suggestion right

**Comment by oshybystyi** [comment]
@audy I think - go ahead an create wiki page, because according to my subjective analysis the level of pros exceeds the level of possible cons :)

**Comment by ncanceill** [comment]
Just a separate section (at the end) for external themes seems good to me.

**Comment by oshybystyi** [comment]
@audy can you create a gist for your theme and add link to https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes

I have also added link to [here](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#more-themes)

You can also change it the way it is pretty to you.

**Comment by audy** [comment]
Done. Thanks @oshybystyi!

**Comment by oshybystyi** [comment]
@audy can you update your gist like [here](https://gist.github.com/oshybystyi/2c30543cd48b2c9ecab0) - I think it is much better that way.

**Comment by oshybystyi** [comment]
@audy ,actually remove README.md and add this info as a comment

**Comment by oshybystyi** [comment]
@audy, nevermind. I've added link to my gist.

**Comment by audy** [comment]
thanks @oshybystyi

**Pull request closed without merging**
